# Generated by Django 6.0.2 on 2026-03-03 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foot_width', models.CharField(choices=[('narrow', '좁음'), ('normal', '보통'), ('wide', '넓음'), ('extra_wide', '매우 넓음')], default='normal', max_length=20, verbose_name='발볼')),
                ('pronation', models.CharField(choices=[('overpronation', '과내전'), ('neutral', '중립'), ('supination', '과외전')], default='neutral', max_length=20, verbose_name='발 유형')),
                ('usage_type', models.CharField(choices=[('beginner', '입문자'), ('daily', '데일리'), ('tempo', '템포'), ('race', '레이스')], default='daily', max_length=20, verbose_name='주 용도')),
                ('budget_min', models.IntegerField(default=0, verbose_name='예산 최소')),
                ('budget_max', models.IntegerField(default=300000, verbose_name='예산 최대')),
                ('priority', models.CharField(choices=[('cushion', '쿠션'), ('speed', '속도'), ('design', '디자인')], default='cushion', max_length=20, verbose_name='우선순위')),
                ('total_km', models.IntegerField(default=0, verbose_name='총 주행거리')),
                ('strava_proof_url', models.URLField(blank=True, verbose_name='스트라바 인증 URL')),
                ('badge', models.CharField(choices=[('none', '일반'), ('verified', '검증러너'), ('reviewer', '리뷰어'), ('master', '마스터'), ('pioneer', '파이오니어')], default='none', max_length=20, verbose_name='배지')),
                ('review_weight', models.FloatField(default=1.0, verbose_name='리뷰 가중치')),
                ('review_count', models.IntegerField(default=0, verbose_name='리뷰 수')),
                ('dispute_accepted_count', models.IntegerField(default=0, verbose_name='채택된 이의제기 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필',
            },
        ),
    ]
