# Generated by Django 6.0.2 on 2026-03-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 (KR, US, JP...)', max_length=2, verbose_name='국가'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語'), ('zh', '中文')], default='ko', max_length=5, verbose_name='선호 언어'),
        ),
    ]
