# Generated by Django 6.0.2 on 2026-03-03 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='슬러그')),
                ('icon', models.CharField(default='📦', max_length=10, verbose_name='아이콘')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('spec_definitions', models.JSONField(blank=True, default=list, help_text='카테고리별 스펙 필드 정의 (JSON 배열)', verbose_name='스펙 정의')),
                ('score_definitions', models.JSONField(blank=True, default=list, help_text='카테고리별 점수 필드 정의 (JSON 배열)', verbose_name='점수 정의')),
                ('brand_score_definitions', models.JSONField(blank=True, default=list, help_text='브랜드 티어 점수 가중치 정의 (JSON 배열)', verbose_name='브랜드 점수 정의')),
                ('quiz_definitions', models.JSONField(blank=True, default=list, help_text='카테고리별 퀴즈 질문 정의 (JSON 배열)', verbose_name='퀴즈 정의')),
                ('filter_definitions', models.JSONField(blank=True, default=dict, help_text='카테고리별 필터 선택지 정의 (JSON 객체)', verbose_name='필터 정의')),
                ('display_order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='브랜드명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='슬러그')),
                ('logo_url', models.URLField(blank=True, verbose_name='로고 URL')),
                ('tier', models.CharField(choices=[('S', 'S티어'), ('A', 'A티어'), ('B', 'B티어'), ('C', 'C티어'), ('D', 'D티어')], default='C', max_length=1, verbose_name='티어')),
                ('tier_score', models.FloatField(default=0.0, verbose_name='티어 점수')),
                ('lineup_score', models.FloatField(default=0.0, verbose_name='라인업 점수')),
                ('tech_score', models.FloatField(default=0.0, verbose_name='기술력 점수')),
                ('durability_score', models.FloatField(default=0.0, verbose_name='내구성 점수')),
                ('community_score', models.FloatField(default=0.0, verbose_name='커뮤니티 점수')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='brands.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드',
                'ordering': ['-tier_score', 'name'],
                'indexes': [models.Index(fields=['slug'], name='brands_bran_slug_5c6464_idx'), models.Index(fields=['tier'], name='brands_bran_tier_d59558_idx'), models.Index(fields=['category'], name='brands_bran_categor_396f80_idx')],
            },
        ),
    ]
