# Generated by Django 6.0.2 on 2026-03-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_config',
            field=models.JSONField(blank=True, default=dict, help_text='프론트엔드 표시 설정 (color, heroTitle, heroDescription 등)', verbose_name='표시 설정'),
        ),
        migrations.CreateModel(
            name='BrandScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='점수 키')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='표시 이름')),
                ('value', models.FloatField(default=0.0, verbose_name='점수 (0-100)')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='brands.brand', verbose_name='브랜드')),
            ],
            options={
                'verbose_name': '브랜드 점수',
                'verbose_name_plural': '브랜드 점수',
                'unique_together': {('brand', 'key')},
            },
        ),
    ]
