# Generated by Django 6.0.2 on 2026-03-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_category_display_config_brandscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(blank=True, choices=[('sports', '스포츠'), ('food', '음식'), ('tech', '테크'), ('lifestyle', '라이프')], default='', help_text='카테고리 그룹 (6개 이상일 때 탭 필터로 표시)', max_length=30, verbose_name='그룹'),
        ),
    ]
