# Generated by Django 6.0.2 on 2026-03-03 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default=uuid.uuid4, max_length=100, unique=True, verbose_name='세션 키')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='퀴즈 답변 (카테고리 quiz_definitions 기반)')),
                ('budget_max', models.IntegerField(blank=True, null=True, verbose_name='예산 최대')),
                ('recommended_products', models.JSONField(blank=True, default=list, verbose_name='추천 제품 ID 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='brands.category', verbose_name='카테고리')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '퀴즈 세션',
                'verbose_name_plural': '퀴즈 세션',
                'ordering': ['-created_at'],
            },
        ),
    ]
