# Generated by Django 6.0.2 on 2026-03-03 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fit_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='착화감 점수')),
                ('width_score', models.CharField(choices=[('narrow', '좁음'), ('normal', '적당함'), ('wide', '넓음')], max_length=20, verbose_name='발볼 평가')),
                ('size_fit', models.CharField(choices=[('half_up', '반 사이즈 업'), ('true', '정사이즈'), ('half_down', '반 사이즈 다운')], max_length=20, verbose_name='사이즈 핏')),
                ('usage_fit', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='용도 적합성')),
                ('pain_level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='통증 레벨')),
                ('durability_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='내구성 점수')),
                ('comment', models.TextField(blank=True, verbose_name='코멘트')),
                ('proof_image_url', models.URLField(blank=True, verbose_name='인증 이미지 URL')),
                ('running_km_at_review', models.IntegerField(default=0, verbose_name='작성 시점 주행거리')),
                ('weight_multiplier', models.FloatField(default=1.0, verbose_name='가중치')),
                ('is_visible', models.BooleanField(default=True, verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='models_app.product', verbose_name='제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='reviews_rev_product_a9ee0d_idx'), models.Index(fields=['user'], name='reviews_rev_user_id_a65d48_idx')],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
