# Generated by Django 6.0.2 on 2026-03-03 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='제품명')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='슬러그')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('tier', models.CharField(choices=[('S', 'S티어'), ('A', 'A티어'), ('B', 'B티어'), ('C', 'C티어'), ('D', 'D티어')], default='C', max_length=1, verbose_name='티어')),
                ('tier_score', models.FloatField(default=0.0, verbose_name='티어 점수')),
                ('community_tier', models.CharField(blank=True, choices=[('S', 'S티어'), ('A', 'A티어'), ('B', 'B티어'), ('C', 'C티어'), ('D', 'D티어')], max_length=1, null=True, verbose_name='커뮤니티 티어')),
                ('product_type', models.CharField(blank=True, max_length=50, verbose_name='제품 타입')),
                ('usage', models.CharField(blank=True, max_length=50, verbose_name='용도')),
                ('price_min', models.IntegerField(default=0, verbose_name='최저가')),
                ('price_max', models.IntegerField(default=0, verbose_name='최고가')),
                ('coupang_link', models.URLField(blank=True, verbose_name='쿠팡 링크')),
                ('naver_link', models.URLField(blank=True, verbose_name='네이버 링크')),
                ('release_year', models.IntegerField(blank=True, null=True, verbose_name='출시년도')),
                ('version_number', models.IntegerField(default=1, verbose_name='버전')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand', verbose_name='브랜드')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.category', verbose_name='카테고리')),
                ('prev_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='models_app.product', verbose_name='이전 버전')),
            ],
            options={
                'verbose_name': '제품',
                'verbose_name_plural': '제품',
                'ordering': ['-tier_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='점수 키')),
                ('value', models.FloatField(default=0.0, verbose_name='점수')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='models_app.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 점수',
                'verbose_name_plural': '제품 점수',
            },
        ),
        migrations.CreateModel(
            name='ProductSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='스펙 키')),
                ('value', models.CharField(max_length=200, verbose_name='값')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='models_app.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 스펙',
                'verbose_name_plural': '제품 스펙',
            },
        ),
        migrations.CreateModel(
            name='ProductTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trap_type', models.CharField(max_length=50, verbose_name='함정 유형')),
                ('trap_description', models.TextField(verbose_name='함정 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traps', to='models_app.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '제품 함정',
                'verbose_name_plural': '제품 함정',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='models_app__slug_de8882_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tier'], name='models_app__tier_bdfeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'usage'], name='models_app__product_939510_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='models_app__categor_c19a43_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='models_app__brand_i_0555a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productscore',
            unique_together={('product', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='productspec',
            unique_together={('product', 'key')},
        ),
    ]
