# Generated by Django 6.0.2 on 2026-03-13 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0003_post_tag_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '제품 좋아요',
                'verbose_name_plural': '제품 좋아요',
            },
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='models_app__categor_80883c_idx',
            old_name='models_app__cat_tag_created_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='models_app__product_63fe33_idx',
            old_name='models_app__product_created_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='평점'),
        ),
        migrations.AddField(
            model_name='product',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='좋아요 수'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='models_app.product', verbose_name='제품'),
        ),
        migrations.AddField(
            model_name='productlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('product', 'user')},
        ),
    ]
