# Generated by Django 6.0.2 on 2026-03-13 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_add_category_group'),
        ('models_app', '0004_add_product_likes_views_and_post_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-is_notice', '-created_at'], name='models_app__categor_359a2f_idx'),
        ),
    ]
