# Generated by Django 6.0.2 on 2026-03-18 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_app', '0006_add_postcomment_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='postcomment',
            new_name='models_app__post_id_07bc41_idx',
            old_name='models_app__post_cr_idx',
        ),
        migrations.RenameIndex(
            model_name='postcomment',
            new_name='models_app__parent__915863_idx',
            old_name='models_app__parent_idx',
        ),
    ]
