# Generated by Django 6.0.2 on 2026-03-03 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TierDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_type', models.CharField(choices=[('upgrade', '승급'), ('downgrade', '강등')], max_length=20, verbose_name='이의제기 유형')),
                ('reason', models.TextField(verbose_name='사유')),
                ('evidence_url', models.URLField(blank=True, verbose_name='증거 URL')),
                ('support_count', models.IntegerField(default=0, verbose_name='찬성 수')),
                ('oppose_count', models.IntegerField(default=0, verbose_name='반대 수')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('colosseum', '콜로세움'), ('resolved', '해결됨'), ('rejected', '거절됨')], default='pending', max_length=20, verbose_name='상태')),
                ('resolution', models.TextField(blank=True, verbose_name='결과')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='models_app.product', verbose_name='제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to=settings.AUTH_USER_MODEL, verbose_name='제출자')),
            ],
            options={
                'verbose_name': '티어 이의제기',
                'verbose_name_plural': '티어 이의제기',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('support', '찬성'), ('oppose', '반대')], max_length=10, verbose_name='투표')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='투표일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_votes', to=settings.AUTH_USER_MODEL, verbose_name='투표자')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tiers.tierdispute', verbose_name='이의제기')),
            ],
            options={
                'verbose_name': '이의제기 투표',
                'verbose_name_plural': '이의제기 투표',
            },
        ),
        migrations.CreateModel(
            name='TrendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('weekly', '주간'), ('monthly', '월간')], max_length=10, verbose_name='기간')),
                ('score', models.FloatField(verbose_name='점수')),
                ('prev_score', models.FloatField(default=0.0, verbose_name='이전 점수')),
                ('trend', models.CharField(choices=[('up', '상승'), ('down', '하락'), ('stable', '유지')], default='stable', max_length=10, verbose_name='추세')),
                ('rank', models.IntegerField(default=0, verbose_name='순위')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='기록일')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trend_logs', to='models_app.product', verbose_name='제품')),
            ],
            options={
                'verbose_name': '트렌드 로그',
                'verbose_name_plural': '트렌드 로그',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tierdispute',
            index=models.Index(fields=['status', 'support_count'], name='tiers_tierd_status_8feb53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='disputevote',
            unique_together={('dispute', 'user')},
        ),
        migrations.AddIndex(
            model_name='trendlog',
            index=models.Index(fields=['product', 'period', 'recorded_at'], name='tiers_trend_product_46af7c_idx'),
        ),
    ]
