# Generated by Django 6.0.2 on 2026-03-06 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTierChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('tier_data', models.JSONField(default=dict, verbose_name='티어 데이터')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('comment_count', models.IntegerField(default=0, verbose_name='댓글 수')),
                ('visibility', models.CharField(choices=[('public', '공개'), ('private', '비공개')], default='public', max_length=20, verbose_name='공개 상태')),
                ('is_featured', models.BooleanField(default=False, verbose_name='추천 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_charts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '사용자 계급도',
                'verbose_name_plural': '사용자 계급도',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TierChartLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_chart_likes', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('tier_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tiers.usertierchart', verbose_name='계급도')),
            ],
            options={
                'verbose_name': '계급도 좋아요',
                'verbose_name_plural': '계급도 좋아요',
            },
        ),
        migrations.CreateModel(
            name='TierChartComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='내용')),
                ('like_count', models.IntegerField(default=0, verbose_name='좋아요 수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tiers.tierchartcomment', verbose_name='상위 댓글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_chart_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('tier_chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tiers.usertierchart', verbose_name='계급도')),
            ],
            options={
                'verbose_name': '계급도 댓글',
                'verbose_name_plural': '계급도 댓글',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usertierchart',
            index=models.Index(fields=['user', '-created_at'], name='tiers_usert_user_id_a49762_idx'),
        ),
        migrations.AddIndex(
            model_name='usertierchart',
            index=models.Index(fields=['visibility', '-like_count'], name='tiers_usert_visibil_146cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='usertierchart',
            index=models.Index(fields=['-view_count'], name='tiers_usert_view_co_69e1c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tierchartlike',
            unique_together={('tier_chart', 'user')},
        ),
    ]
