# Generated by Django 6.0.2 on 2026-03-10 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0002_usertierchart_tierchartlike_tierchartcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertierchart',
            name='promoted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='승격일'),
        ),
        migrations.AddField(
            model_name='usertierchart',
            name='promoted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_tier_charts', to=settings.AUTH_USER_MODEL, verbose_name='승격 처리자'),
        ),
        migrations.AddField(
            model_name='usertierchart',
            name='promotion_status',
            field=models.CharField(choices=[('normal', '일반'), ('rising', '급상승'), ('candidate', '승급 후보'), ('promoted', '승급됨')], default='normal', max_length=20, verbose_name='승격 상태'),
        ),
        migrations.AddIndex(
            model_name='usertierchart',
            index=models.Index(fields=['promotion_status', '-created_at'], name='tiers_usert_promoti_149d20_idx'),
        ),
    ]
