# Generated by Django 6.0.2 on 2026-03-10 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0003_usertierchart_promoted_at_usertierchart_promoted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertierchart',
            name='author_country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 (KR, US, JP...)', max_length=2, verbose_name='작성자 국가'),
        ),
        migrations.AddField(
            model_name='usertierchart',
            name='is_global',
            field=models.BooleanField(default=True, help_text='False면 해당 언어권에서만 노출', verbose_name='글로벌 노출'),
        ),
        migrations.AddField(
            model_name='usertierchart',
            name='language',
            field=models.CharField(choices=[('ko', '한국어'), ('en', 'English'), ('ja', '日本語'), ('zh', '中文')], default='ko', max_length=5, verbose_name='언어'),
        ),
        migrations.AddIndex(
            model_name='usertierchart',
            index=models.Index(fields=['language', '-created_at'], name='tiers_usert_languag_e87a84_idx'),
        ),
    ]
