# Generated by Django 6.0.2 on 2026-03-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiers', '0004_add_language_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertierchart',
            name='converted_category_slug',
            field=models.CharField(blank=True, default='', help_text='공식 계급도로 전환된 경우 해당 카테고리 슬러그', max_length=100, verbose_name='전환된 카테고리 슬러그'),
        ),
        migrations.AddField(
            model_name='usertierchart',
            name='converted_to_official',
            field=models.BooleanField(default=False, verbose_name='공식 계급도 전환 여부'),
        ),
        migrations.AddField(
            model_name='usertierchart',
            name='hall_of_fame_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='명예의 전당 등록일'),
        ),
        migrations.AddField(
            model_name='usertierchart',
            name='hot_until',
            field=models.DateTimeField(blank=True, help_text='이 날짜까지 홈페이지 HOT 섹션에 노출', null=True, verbose_name='HOT 노출 종료일'),
        ),
        migrations.AlterField(
            model_name='usertierchart',
            name='promotion_status',
            field=models.CharField(choices=[('normal', '일반'), ('rising', '급상승'), ('candidate', '승급 후보'), ('promoted', '승급됨'), ('hall_of_fame', '명예의 전당')], default='normal', max_length=20, verbose_name='승격 상태'),
        ),
    ]
