"""
제품 시드 데이터 생성 커맨드.
사용: python manage.py seed_products
"""
from django.core.management.base import BaseCommand
from brands.models import Category, Brand
from models_app.models import Product, ProductSpec, ProductScore


# ============================================================================
# 러닝화 제품 데이터
# ============================================================================
RUNNING_SHOES_DATA = [
    # ---- 나이키 ----
    {
        'brand_slug': 'nike',
        'name': 'Vaporfly 3',
        'slug': 'nike-vaporfly-3',
        'description': '나이키 최고의 레이싱 슈즈. ZoomX 폼과 풀렝스 카본 플레이트로 최상의 에너지 리턴 제공',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 310000,
        'release_year': 2023,
        'version_number': 3,
        'specs': {'weight': '188', 'stack_height': '40', 'drop': '8', 'upper': '플라이니트', 'midsole': 'ZoomX + 카본 플레이트'},
        'scores': {'cushion': 95, 'responsiveness': 98, 'stability': 75, 'durability': 70},
    },
    {
        'brand_slug': 'nike',
        'name': 'Alphafly 3',
        'slug': 'nike-alphafly-3',
        'description': '킵초게가 세계기록을 세운 슈즈의 후속작. 에어줌 유닛과 카본 플레이트 조합',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 350000,
        'price_max': 380000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '212', 'stack_height': '40', 'drop': '4', 'upper': '아토미니트', 'midsole': 'ZoomX + Air Zoom + 카본'},
        'scores': {'cushion': 98, 'responsiveness': 96, 'stability': 72, 'durability': 68},
    },
    {
        'brand_slug': 'nike',
        'name': 'Pegasus 41',
        'slug': 'nike-pegasus-41',
        'description': '나이키 대표 데일리 트레이너. 40년 역사의 검증된 라인업',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 149000,
        'price_max': 169000,
        'release_year': 2024,
        'version_number': 41,
        'specs': {'weight': '272', 'stack_height': '28', 'drop': '10', 'upper': '메쉬', 'midsole': 'React X'},
        'scores': {'cushion': 85, 'responsiveness': 78, 'stability': 82, 'durability': 85},
    },
    {
        'brand_slug': 'nike',
        'name': 'Structure 26',
        'slug': 'nike-structure-26',
        'description': '안정화 러닝화의 기준. 내측 지지대로 오버프로네이션 방지',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 139000,
        'price_max': 159000,
        'release_year': 2024,
        'version_number': 26,
        'specs': {'weight': '285', 'stack_height': '26', 'drop': '10', 'upper': '메쉬', 'midsole': 'React X + 미드풋 지지대'},
        'scores': {'cushion': 80, 'responsiveness': 72, 'stability': 92, 'durability': 85},
    },
    # ---- 아식스 ----
    {
        'brand_slug': 'asics',
        'name': 'Metaspeed Sky+',
        'slug': 'asics-metaspeed-sky-plus',
        'description': '스트라이드 러너를 위한 레이싱 슈즈. FF BLAST TURBO와 카본 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 290000,
        'price_max': 320000,
        'release_year': 2023,
        'version_number': 2,
        'specs': {'weight': '195', 'stack_height': '38', 'drop': '5', 'upper': '모션랩 어퍼', 'midsole': 'FF BLAST TURBO + 카본'},
        'scores': {'cushion': 90, 'responsiveness': 94, 'stability': 80, 'durability': 75},
    },
    {
        'brand_slug': 'asics',
        'name': 'Metaspeed Edge+',
        'slug': 'asics-metaspeed-edge-plus',
        'description': '케이던스 러너를 위한 레이싱 슈즈. 빠른 회전율에 최적화',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 290000,
        'price_max': 320000,
        'release_year': 2023,
        'version_number': 2,
        'specs': {'weight': '190', 'stack_height': '33', 'drop': '5', 'upper': '모션랩 어퍼', 'midsole': 'FF BLAST TURBO + 카본'},
        'scores': {'cushion': 85, 'responsiveness': 96, 'stability': 82, 'durability': 74},
    },
    {
        'brand_slug': 'asics',
        'name': 'Gel Nimbus 26',
        'slug': 'asics-gel-nimbus-26',
        'description': '아식스 프리미엄 쿠션화. GEL 기술과 FF BLAST PLUS로 최상의 편안함',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 189000,
        'price_max': 210000,
        'release_year': 2024,
        'version_number': 26,
        'specs': {'weight': '290', 'stack_height': '35', 'drop': '8', 'upper': '엔지니어드 메쉬', 'midsole': 'FF BLAST PLUS + GEL'},
        'scores': {'cushion': 92, 'responsiveness': 72, 'stability': 85, 'durability': 88},
    },
    {
        'brand_slug': 'asics',
        'name': 'Gel Kayano 31',
        'slug': 'asics-gel-kayano-31',
        'description': '30년 역사의 안정화 명가. 4D 가이드 시스템으로 완벽한 지지력',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 199000,
        'price_max': 220000,
        'release_year': 2024,
        'version_number': 31,
        'specs': {'weight': '305', 'stack_height': '35', 'drop': '10', 'upper': '엔지니어드 메쉬', 'midsole': 'FF BLAST PLUS + 4D 가이드'},
        'scores': {'cushion': 88, 'responsiveness': 70, 'stability': 95, 'durability': 90},
    },
    {
        'brand_slug': 'asics',
        'name': 'Novablast 5',
        'slug': 'asics-novablast-5',
        'description': '경쾌한 반발력의 데일리 트레이너. FF BLAST PLUS 폼의 탄성',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 5,
        'specs': {'weight': '255', 'stack_height': '32', 'drop': '8', 'upper': '메쉬', 'midsole': 'FF BLAST PLUS'},
        'scores': {'cushion': 86, 'responsiveness': 85, 'stability': 75, 'durability': 82},
    },
    # ---- 호카 ----
    {
        'brand_slug': 'hoka',
        'name': 'Rocket X2',
        'slug': 'hoka-rocket-x2',
        'description': '호카의 레이싱 슈퍼슈즈. PEBA 폼과 카본 플레이트 조합',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2023,
        'version_number': 2,
        'specs': {'weight': '205', 'stack_height': '38', 'drop': '5', 'upper': '크릴 메쉬', 'midsole': 'PEBA + 카본 플레이트'},
        'scores': {'cushion': 88, 'responsiveness': 90, 'stability': 78, 'durability': 75},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Cielo X1',
        'slug': 'hoka-cielo-x1',
        'description': '호카의 최신 카본 레이서. 빠른 러너를 위한 최경량 설계',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 300000,
        'price_max': 330000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '178', 'stack_height': '39', 'drop': '5', 'upper': '크릴 메쉬', 'midsole': 'PEBA + 카본 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 94, 'stability': 75, 'durability': 72},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Clifton 9',
        'slug': 'hoka-clifton-9',
        'description': '호카 대표 데일리 트레이너. 맥시멀 쿠셔닝의 정석',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2023,
        'version_number': 9,
        'specs': {'weight': '248', 'stack_height': '32', 'drop': '5', 'upper': '엔지니어드 메쉬', 'midsole': 'CMEVA'},
        'scores': {'cushion': 90, 'responsiveness': 75, 'stability': 80, 'durability': 82},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Bondi 8',
        'slug': 'hoka-bondi-8',
        'description': '호카 최고의 쿠셔닝. 장거리 러닝에 최적화된 맥시멀 쿠션',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2023,
        'version_number': 8,
        'specs': {'weight': '307', 'stack_height': '37', 'drop': '4', 'upper': '엔지니어드 메쉬', 'midsole': 'CMEVA'},
        'scores': {'cushion': 95, 'responsiveness': 68, 'stability': 78, 'durability': 85},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Mach 6',
        'slug': 'hoka-mach-6',
        'description': '템포런에 최적화된 경량 트레이너. PEBA 폼 적용',
        'product_type': 'speed',
        'usage': 'tempo',
        'price_min': 169000,
        'price_max': 189000,
        'release_year': 2024,
        'version_number': 6,
        'specs': {'weight': '232', 'stack_height': '32', 'drop': '5', 'upper': '엔지니어드 메쉬', 'midsole': 'PEBA'},
        'scores': {'cushion': 82, 'responsiveness': 88, 'stability': 78, 'durability': 78},
    },
    # ---- 뉴발란스 ----
    {
        'brand_slug': 'new-balance',
        'name': 'SC Elite v4',
        'slug': 'new-balance-sc-elite-v4',
        'description': '뉴발란스 플래그십 레이서. FuelCell 슈퍼컴프 엘리트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 320000,
        'price_max': 350000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '198', 'stack_height': '38', 'drop': '8', 'upper': '뉴메쉬', 'midsole': 'FuelCell + 카본 플레이트'},
        'scores': {'cushion': 92, 'responsiveness': 93, 'stability': 76, 'durability': 72},
    },
    {
        'brand_slug': 'new-balance',
        'name': 'FuelCell Rebel v4',
        'slug': 'new-balance-fuelcell-rebel-v4',
        'description': '템포런과 데일리 트레이닝에 최적. 경쾌한 반발력',
        'product_type': 'cushion',
        'usage': 'tempo',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '228', 'stack_height': '30', 'drop': '6', 'upper': '메쉬', 'midsole': 'FuelCell'},
        'scores': {'cushion': 85, 'responsiveness': 88, 'stability': 78, 'durability': 80},
    },
    {
        'brand_slug': 'new-balance',
        'name': 'Fresh Foam 1080v13',
        'slug': 'new-balance-fresh-foam-1080-v13',
        'description': '뉴발란스 프리미엄 데일리 트레이너. Fresh Foam X 적용',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2023,
        'version_number': 13,
        'specs': {'weight': '280', 'stack_height': '34', 'drop': '6', 'upper': '하이포니트', 'midsole': 'Fresh Foam X'},
        'scores': {'cushion': 90, 'responsiveness': 75, 'stability': 82, 'durability': 85},
    },
    {
        'brand_slug': 'new-balance',
        'name': 'Fresh Foam 860v14',
        'slug': 'new-balance-fresh-foam-860-v14',
        'description': '안정화 데일리 트레이너. 내측 포스팅으로 오버프로네이션 지원',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 169000,
        'price_max': 189000,
        'release_year': 2024,
        'version_number': 14,
        'specs': {'weight': '295', 'stack_height': '32', 'drop': '10', 'upper': '메쉬', 'midsole': 'Fresh Foam X + 포스팅'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 90, 'durability': 86},
    },
    # ---- 아디다스 ----
    {
        'brand_slug': 'adidas',
        'name': 'Adizero Adios Pro 3',
        'slug': 'adidas-adizero-adios-pro-3',
        'description': '아디다스 플래그십 레이서. 라이트스트라이크 프로와 에너지 로드',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 300000,
        'price_max': 330000,
        'release_year': 2023,
        'version_number': 3,
        'specs': {'weight': '215', 'stack_height': '39', 'drop': '6.5', 'upper': '라이트웨이트 메쉬', 'midsole': 'Lightstrike Pro + 에너지 로드'},
        'scores': {'cushion': 92, 'responsiveness': 95, 'stability': 78, 'durability': 72},
    },
    {
        'brand_slug': 'adidas',
        'name': 'Adizero Boston 12',
        'slug': 'adidas-adizero-boston-12',
        'description': '템포런에 최적화된 트레이너. 에너지 로드 2.0 적용',
        'product_type': 'cushion',
        'usage': 'tempo',
        'price_min': 180000,
        'price_max': 200000,
        'release_year': 2024,
        'version_number': 12,
        'specs': {'weight': '235', 'stack_height': '33', 'drop': '6.5', 'upper': '엔지니어드 메쉬', 'midsole': 'Lightstrike Pro + 에너지 로드 2.0'},
        'scores': {'cushion': 82, 'responsiveness': 88, 'stability': 85, 'durability': 80},
    },
    {
        'brand_slug': 'adidas',
        'name': 'Ultraboost Light',
        'slug': 'adidas-ultraboost-light',
        'description': '아디다스 아이코닉 데일리 러너. 라이트 부스트 적용으로 경량화',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 199000,
        'price_max': 230000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '275', 'stack_height': '29', 'drop': '10', 'upper': '프라임니트', 'midsole': 'Light Boost'},
        'scores': {'cushion': 88, 'responsiveness': 78, 'stability': 80, 'durability': 82},
    },
    {
        'brand_slug': 'adidas',
        'name': 'Supernova Rise',
        'slug': 'adidas-supernova-rise',
        'description': '입문자용 데일리 트레이너. 드림스트라이크+ 폼 적용',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 139000,
        'price_max': 159000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '295', 'stack_height': '30', 'drop': '10', 'upper': '메쉬', 'midsole': 'Dreamstrike+'},
        'scores': {'cushion': 82, 'responsiveness': 72, 'stability': 85, 'durability': 88},
    },
    # ---- 써코니 ----
    {
        'brand_slug': 'saucony',
        'name': 'Endorphin Pro 4',
        'slug': 'saucony-endorphin-pro-4',
        'description': '써코니 플래그십 레이서. 파워런 PB와 카본 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '195', 'stack_height': '38', 'drop': '8', 'upper': '슬림 메쉬', 'midsole': 'PWRRUN PB + 카본 플레이트'},
        'scores': {'cushion': 90, 'responsiveness': 94, 'stability': 76, 'durability': 72},
    },
    {
        'brand_slug': 'saucony',
        'name': 'Endorphin Speed 4',
        'slug': 'saucony-endorphin-speed-4',
        'description': '템포와 레이스 겸용. 나일론 플레이트로 안정적인 추진력',
        'product_type': 'speed',
        'usage': 'tempo',
        'price_min': 200000,
        'price_max': 220000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '215', 'stack_height': '36', 'drop': '8', 'upper': '메쉬', 'midsole': 'PWRRUN PB + 나일론 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 90, 'stability': 82, 'durability': 78},
    },
    {
        'brand_slug': 'saucony',
        'name': 'Triumph 22',
        'slug': 'saucony-triumph-22',
        'description': '써코니 프리미엄 데일리 트레이너. PWRRUN+ 쿠셔닝',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2024,
        'version_number': 22,
        'specs': {'weight': '283', 'stack_height': '32', 'drop': '10', 'upper': 'FORMFIT', 'midsole': 'PWRRUN+'},
        'scores': {'cushion': 92, 'responsiveness': 75, 'stability': 82, 'durability': 85},
    },
    {
        'brand_slug': 'saucony',
        'name': 'Guide 17',
        'slug': 'saucony-guide-17',
        'description': '안정화 러너의 선택. 내측 지지대로 과회전 방지',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 17,
        'specs': {'weight': '275', 'stack_height': '30', 'drop': '8', 'upper': 'FORMFIT', 'midsole': 'PWRRUN + 내측 지지대'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 90, 'durability': 85},
    },
    # ---- 브룩스 ----
    {
        'brand_slug': 'brooks',
        'name': 'Hyperion Elite 4',
        'slug': 'brooks-hyperion-elite-4',
        'description': '브룩스 레이싱 슈퍼슈즈. DNA FLASH와 카본 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '198', 'stack_height': '36', 'drop': '8', 'upper': '라이트웨이트 어퍼', 'midsole': 'DNA FLASH + 카본 플레이트'},
        'scores': {'cushion': 88, 'responsiveness': 92, 'stability': 78, 'durability': 72},
    },
    {
        'brand_slug': 'brooks',
        'name': 'Glycerin 21',
        'slug': 'brooks-glycerin-21',
        'description': '브룩스 최고의 쿠셔닝. DNA LOFT v3로 부드러운 착지감',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 189000,
        'price_max': 210000,
        'release_year': 2024,
        'version_number': 21,
        'specs': {'weight': '290', 'stack_height': '34', 'drop': '10', 'upper': '엔지니어드 메쉬', 'midsole': 'DNA LOFT v3'},
        'scores': {'cushion': 95, 'responsiveness': 72, 'stability': 80, 'durability': 88},
    },
    {
        'brand_slug': 'brooks',
        'name': 'Ghost 16',
        'slug': 'brooks-ghost-16',
        'description': '브룩스 베스트셀러 데일리 트레이너. 균형잡힌 쿠셔닝',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 149000,
        'price_max': 169000,
        'release_year': 2024,
        'version_number': 16,
        'specs': {'weight': '278', 'stack_height': '32', 'drop': '12', 'upper': '메쉬', 'midsole': 'DNA LOFT'},
        'scores': {'cushion': 88, 'responsiveness': 75, 'stability': 82, 'durability': 88},
    },
    {
        'brand_slug': 'brooks',
        'name': 'Adrenaline GTS 24',
        'slug': 'brooks-adrenaline-gts-24',
        'description': '안정화의 기준. GuideRails로 발의 움직임 제어',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 24,
        'specs': {'weight': '285', 'stack_height': '32', 'drop': '12', 'upper': '메쉬', 'midsole': 'DNA LOFT + GuideRails'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 92, 'durability': 88},
    },
    # ---- 푸마 ----
    {
        'brand_slug': 'puma',
        'name': 'Deviate Nitro Elite 4',
        'slug': 'puma-deviate-nitro-elite-4',
        'description': '푸마 플래그십 레이서. 170g 초경량 카본 슈퍼슈즈',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2026,
        'version_number': 4,
        'specs': {'weight': '170', 'stack_height': '38', 'drop': '7', 'upper': '울트라 라이트 메쉬', 'midsole': 'NITROFOAM Elite + 카본'},
        'scores': {'cushion': 85, 'responsiveness': 95, 'stability': 75, 'durability': 70},
    },
    {
        'brand_slug': 'puma',
        'name': 'Deviate Nitro 4',
        'slug': 'puma-deviate-nitro-4',
        'description': '템포와 대회 겸용 트레이너. 듀얼 레이어 나이트로폼',
        'product_type': 'speed',
        'usage': 'tempo',
        'price_min': 180000,
        'price_max': 200000,
        'release_year': 2026,
        'version_number': 4,
        'specs': {'weight': '225', 'stack_height': '35', 'drop': '7', 'upper': '엔지니어드 니트', 'midsole': 'NITROFOAM + PWRPLATE'},
        'scores': {'cushion': 85, 'responsiveness': 88, 'stability': 82, 'durability': 78},
    },
    {
        'brand_slug': 'puma',
        'name': 'Velocity Nitro 3',
        'slug': 'puma-velocity-nitro-3',
        'description': '푸마 데일리 트레이너. 가성비 뛰어난 나이트로 폼',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 139000,
        'price_max': 159000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '265', 'stack_height': '30', 'drop': '10', 'upper': '메쉬', 'midsole': 'NITROFOAM'},
        'scores': {'cushion': 82, 'responsiveness': 78, 'stability': 80, 'durability': 85},
    },
    # ---- 온러닝 ----
    {
        'brand_slug': 'on-running',
        'name': 'Cloudboom Strike',
        'slug': 'on-cloudboom-strike',
        'description': '온러닝 레이싱 슈즈. Helion HF와 Speedboard',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 290000,
        'price_max': 320000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '215', 'stack_height': '38', 'drop': '9', 'upper': '엔지니어드 메쉬', 'midsole': 'Helion HF + Speedboard'},
        'scores': {'cushion': 85, 'responsiveness': 90, 'stability': 78, 'durability': 75},
    },
    {
        'brand_slug': 'on-running',
        'name': 'Cloudmonster 2',
        'slug': 'on-cloudmonster-2',
        'description': '온러닝 맥시멀 쿠셔닝. CloudTec 구조의 독특한 착지감',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 199000,
        'price_max': 219000,
        'release_year': 2024,
        'version_number': 2,
        'specs': {'weight': '295', 'stack_height': '35', 'drop': '6', 'upper': '엔지니어드 메쉬', 'midsole': 'Helion + CloudTec'},
        'scores': {'cushion': 90, 'responsiveness': 80, 'stability': 78, 'durability': 80},
    },
    {
        'brand_slug': 'on-running',
        'name': 'Cloudstratus 3',
        'slug': 'on-cloudstratus-3',
        'description': '온러닝 안정화 쿠션. 더블 레이어 CloudTec으로 지지력 강화',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '310', 'stack_height': '32', 'drop': '6', 'upper': '엔지니어드 메쉬', 'midsole': 'Helion + 더블 CloudTec'},
        'scores': {'cushion': 88, 'responsiveness': 75, 'stability': 88, 'durability': 82},
    },
    {
        'brand_slug': 'on-running',
        'name': 'Cloudsurfer 7',
        'slug': 'on-cloudsurfer-7',
        'description': '온러닝 데일리 트레이너. 경쾌한 반응성과 쿠셔닝 밸런스',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 169000,
        'price_max': 189000,
        'release_year': 2024,
        'version_number': 7,
        'specs': {'weight': '280', 'stack_height': '29', 'drop': '10', 'upper': '메쉬', 'midsole': 'Helion + CloudTec'},
        'scores': {'cushion': 85, 'responsiveness': 82, 'stability': 80, 'durability': 82},
    },
    # ---- 미즈노 ----
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Rebellion Pro 3',
        'slug': 'mizuno-wave-rebellion-pro-3',
        'description': '미즈노 레이싱 슈퍼슈즈. 미즈노 에너지와 G3 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '200', 'stack_height': '40', 'drop': '4', 'upper': '엔지니어드 메쉬', 'midsole': '미즈노 에너지 + G3 플레이트'},
        'scores': {'cushion': 88, 'responsiveness': 92, 'stability': 78, 'durability': 72},
    },
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Rider 28',
        'slug': 'mizuno-wave-rider-28',
        'description': '미즈노 대표 데일리 트레이너. 웨이브 플레이트로 안정성 확보',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 149000,
        'price_max': 169000,
        'release_year': 2024,
        'version_number': 28,
        'specs': {'weight': '275', 'stack_height': '32', 'drop': '12', 'upper': '에어메쉬', 'midsole': '미즈노 에너지 + 웨이브 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 78, 'stability': 85, 'durability': 88},
    },
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Sky 8',
        'slug': 'mizuno-wave-sky-8',
        'description': '미즈노 프리미엄 쿠션화. 최대 쿠셔닝으로 장거리에 최적',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2024,
        'version_number': 8,
        'specs': {'weight': '310', 'stack_height': '35', 'drop': '10', 'upper': '엔지니어드 메쉬', 'midsole': '미즈노 에너지 + 웨이브 플레이트'},
        'scores': {'cushion': 92, 'responsiveness': 70, 'stability': 82, 'durability': 86},
    },
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Inspire 20',
        'slug': 'mizuno-wave-inspire-20',
        'description': '미즈노 안정화. 웨이브 플레이트로 내측 지지력 강화',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 20,
        'specs': {'weight': '290', 'stack_height': '32', 'drop': '12', 'upper': '에어메쉬', 'midsole': '미즈노 에너지 + 웨이브 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 90, 'durability': 88},
    },
]

# ============================================================================
# 치킨 제품 데이터
# ============================================================================
CHICKEN_DATA = [
    # ---- BBQ ----
    {
        'brand_slug': 'bbq-golden-olive',
        'name': '황금올리브 콤보',
        'slug': 'bbq-golden-olive-combo',
        'description': 'BBQ 시그니처 메뉴. 올리브유로 바삭하게 튀긴 프리미엄 치킨',
        'product_type': 'fried',
        'usage': 'party',
        'price_min': 27000,
        'price_max': 27000,
        'specs': {'price': '27000', 'calories': '1850', 'serving': '1000', 'spicy_level': '없음', 'cooking_method': '올리브유 튀김'},
        'scores': {'taste': 95, 'price': 82, 'crispy': 96, 'popularity': 98},
    },
    {
        'brand_slug': 'bbq-golden-olive',
        'name': '자메이카 통다리 구이',
        'slug': 'bbq-jamaica-drumstick',
        'description': '스모키한 자메이카 스파이스로 구운 통다리 치킨',
        'product_type': 'roasted',
        'usage': 'beer',
        'price_min': 24000,
        'price_max': 24000,
        'specs': {'price': '24000', 'calories': '1450', 'serving': '850', 'spicy_level': '중간', 'cooking_method': '오븐 구이'},
        'scores': {'taste': 92, 'price': 78, 'crispy': 75, 'popularity': 88},
    },
    {
        'brand_slug': 'bbq-golden-olive',
        'name': '황금올리브 블랙페퍼',
        'slug': 'bbq-golden-olive-black-pepper',
        'description': '황금올리브에 블랙페퍼 시즈닝을 더한 스파이시 버전',
        'product_type': 'fried',
        'usage': 'beer',
        'price_min': 21000,
        'price_max': 21000,
        'specs': {'price': '21000', 'calories': '1750', 'serving': '950', 'spicy_level': '약간', 'cooking_method': '올리브유 튀김'},
        'scores': {'taste': 90, 'price': 85, 'crispy': 94, 'popularity': 85},
    },
    # ---- 교촌 ----
    {
        'brand_slug': 'kyochon-original',
        'name': '허니콤보',
        'slug': 'kyochon-honey-combo',
        'description': '꿀과 간장의 조화. 달콤짭짤한 교촌의 베스트셀러',
        'product_type': 'soy',
        'usage': 'family',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1650', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+소스'},
        'scores': {'taste': 94, 'price': 82, 'crispy': 88, 'popularity': 96},
    },
    {
        'brand_slug': 'kyochon-original',
        'name': '레드콤보',
        'slug': 'kyochon-red-combo',
        'description': '매콤한 교촌만의 레드 시즈닝. 매운맛 마니아 필수',
        'product_type': 'seasoned',
        'usage': 'beer',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1700', 'serving': '900', 'spicy_level': '매움', 'cooking_method': '튀김+양념'},
        'scores': {'taste': 92, 'price': 82, 'crispy': 86, 'popularity': 92},
    },
    {
        'brand_slug': 'kyochon-original',
        'name': '교촌오리지날',
        'slug': 'kyochon-original-soy',
        'description': '교촌의 시작. 간장 베이스의 원조 간장치킨',
        'product_type': 'soy',
        'usage': 'family',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1600', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+간장소스'},
        'scores': {'taste': 95, 'price': 80, 'crispy': 85, 'popularity': 95},
    },
    # ---- BHC ----
    {
        'brand_slug': 'bhc-puringkle',
        'name': '뿌링클',
        'slug': 'bhc-puringkle-original',
        'description': 'MZ세대 인기 1위. 치즈 시즈닝과 뿌링뿌링 소스의 환상조합',
        'product_type': 'cheese',
        'usage': 'party',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '2320', 'serving': '1100', 'spicy_level': '없음', 'cooking_method': '튀김+치즈 시즈닝'},
        'scores': {'taste': 94, 'price': 85, 'crispy': 92, 'popularity': 98},
    },
    {
        'brand_slug': 'bhc-puringkle',
        'name': '뿌링클 핫',
        'slug': 'bhc-puringkle-hot',
        'description': '뿌링클에 매직 핫 시즈닝을 더한 매콤 버전',
        'product_type': 'cheese',
        'usage': 'beer',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '2350', 'serving': '1100', 'spicy_level': '매움', 'cooking_method': '튀김+핫 시즈닝'},
        'scores': {'taste': 92, 'price': 85, 'crispy': 90, 'popularity': 90},
    },
    {
        'brand_slug': 'bhc-matchoking',
        'name': '맛초킹',
        'slug': 'bhc-matchoking-original',
        'description': '고추장 베이스의 매콤달콤. 쫄깃한 튀김옷이 특징',
        'product_type': 'seasoned',
        'usage': 'beer',
        'price_min': 21000,
        'price_max': 23000,
        'specs': {'price': '21000', 'calories': '1850', 'serving': '950', 'spicy_level': '매움', 'cooking_method': '튀김+양념'},
        'scores': {'taste': 88, 'price': 82, 'crispy': 82, 'popularity': 85},
    },
    # ---- 굽네 ----
    {
        'brand_slug': 'goobne-gochu',
        'name': '고추바사삭',
        'slug': 'goobne-gochu-basasak',
        'description': '오븐에 구워 담백하고 바삭한 굽네 시그니처',
        'product_type': 'roasted',
        'usage': 'family',
        'price_min': 19900,
        'price_max': 22900,
        'specs': {'price': '19900', 'calories': '1350', 'serving': '800', 'spicy_level': '중간', 'cooking_method': '오븐 구이'},
        'scores': {'taste': 90, 'price': 85, 'crispy': 88, 'popularity': 88},
    },
    {
        'brand_slug': 'goobne-gochu',
        'name': '볼케이노',
        'slug': 'goobne-volcano',
        'description': '화끈하게 매운 굽네의 불닭 메뉴',
        'product_type': 'roasted',
        'usage': 'beer',
        'price_min': 20900,
        'price_max': 22900,
        'specs': {'price': '20900', 'calories': '1450', 'serving': '850', 'spicy_level': '아주 매움', 'cooking_method': '오븐 구이+소스'},
        'scores': {'taste': 85, 'price': 82, 'crispy': 80, 'popularity': 78},
    },
    {
        'brand_slug': 'goobne-gochu',
        'name': '오리지널',
        'slug': 'goobne-original',
        'description': '굽네의 기본. 담백하고 깔끔한 오븐 구이 치킨',
        'product_type': 'roasted',
        'usage': 'family',
        'price_min': 17900,
        'price_max': 20900,
        'specs': {'price': '17900', 'calories': '1200', 'serving': '750', 'spicy_level': '없음', 'cooking_method': '오븐 구이'},
        'scores': {'taste': 85, 'price': 88, 'crispy': 82, 'popularity': 82},
    },
    # ---- 네네 ----
    {
        'brand_slug': 'nene-snowing',
        'name': '치즈스노윙',
        'slug': 'nene-cheese-snowing',
        'description': '눈꽃치즈가 흩날리는 네네의 시그니처',
        'product_type': 'cheese',
        'usage': 'party',
        'price_min': 22000,
        'price_max': 23000,
        'specs': {'price': '22000', 'calories': '2100', 'serving': '1000', 'spicy_level': '없음', 'cooking_method': '튀김+치즈 토핑'},
        'scores': {'taste': 90, 'price': 80, 'crispy': 85, 'popularity': 88},
    },
    {
        'brand_slug': 'nene-snowing',
        'name': '스노윙MAXX',
        'slug': 'nene-snowing-maxx',
        'description': '더 많은 치즈, 더 풍성한 맛. 스노윙의 업그레이드 버전',
        'product_type': 'cheese',
        'usage': 'party',
        'price_min': 23000,
        'price_max': 23000,
        'specs': {'price': '23000', 'calories': '2250', 'serving': '1050', 'spicy_level': '없음', 'cooking_method': '튀김+치즈 토핑'},
        'scores': {'taste': 92, 'price': 78, 'crispy': 85, 'popularity': 85},
    },
    {
        'brand_slug': 'nene-snowing',
        'name': '오리엔탈파닭',
        'slug': 'nene-oriental-padak',
        'description': '파채와 오리엔탈 소스의 조화. 맥주 안주로 최고',
        'product_type': 'fried',
        'usage': 'beer',
        'price_min': 23000,
        'price_max': 23000,
        'specs': {'price': '23000', 'calories': '1800', 'serving': '950', 'spicy_level': '없음', 'cooking_method': '튀김+파채 토핑'},
        'scores': {'taste': 88, 'price': 78, 'crispy': 88, 'popularity': 82},
    },
    # ---- 푸라닭 ----
    {
        'brand_slug': 'puradak-black-allio',
        'name': '블랙알리오',
        'slug': 'puradak-black-allio-original',
        'description': '간장과 마늘의 깊은 풍미. 푸라닭 시그니처 메뉴',
        'product_type': 'garlic',
        'usage': 'beer',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '1750', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+마늘소스'},
        'scores': {'taste': 93, 'price': 78, 'crispy': 88, 'popularity': 85},
    },
    {
        'brand_slug': 'puradak-black-allio',
        'name': '고추마요',
        'slug': 'puradak-gochu-mayo',
        'description': '청양고추와 마요네즈의 조화. 매콤크리미한 맛',
        'product_type': 'seasoned',
        'usage': 'beer',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '1950', 'serving': '900', 'spicy_level': '중간', 'cooking_method': '튀김+마요소스'},
        'scores': {'taste': 90, 'price': 78, 'crispy': 85, 'popularity': 82},
    },
    # ---- 호식이 ----
    {
        'brand_slug': 'hosigi-fried',
        'name': '호식이 후라이드+후라이드',
        'slug': 'hosigi-double-fried',
        'description': '두마리 치킨의 원조. 옛날통닭 스타일 후라이드',
        'product_type': 'fried',
        'usage': 'family',
        'price_min': 25000,
        'price_max': 25000,
        'specs': {'price': '25000', 'calories': '2800', 'serving': '1600', 'spicy_level': '없음', 'cooking_method': '튀김'},
        'scores': {'taste': 80, 'price': 95, 'crispy': 82, 'popularity': 78},
    },
    {
        'brand_slug': 'hosigi-fried',
        'name': '레몬크림탕슈',
        'slug': 'hosigi-lemon-cream',
        'description': '상큼한 레몬과 크리미한 소스. 호식이의 인기 신메뉴',
        'product_type': 'seasoned',
        'usage': 'party',
        'price_min': 26000,
        'price_max': 26000,
        'specs': {'price': '26000', 'calories': '2200', 'serving': '1000', 'spicy_level': '없음', 'cooking_method': '튀김+소스'},
        'scores': {'taste': 82, 'price': 88, 'crispy': 78, 'popularity': 75},
    },
    # ---- 처갓집 ----
    {
        'brand_slug': 'cheogajip-supreme',
        'name': '슈프림골드양념',
        'slug': 'cheogajip-supreme-gold',
        'description': '진하고 달콤한 처갓집 시그니처 양념. 호불호 없는 맛',
        'product_type': 'seasoned',
        'usage': 'family',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1900', 'serving': '950', 'spicy_level': '없음', 'cooking_method': '튀김+양념'},
        'scores': {'taste': 85, 'price': 78, 'crispy': 78, 'popularity': 75},
    },
    {
        'brand_slug': 'cheogajip-supreme',
        'name': '트러플슈프림양념',
        'slug': 'cheogajip-truffle-supreme',
        'description': '트러플 오일이 더해진 프리미엄 버전',
        'product_type': 'seasoned',
        'usage': 'party',
        'price_min': 25000,
        'price_max': 27000,
        'specs': {'price': '25000', 'calories': '1950', 'serving': '950', 'spicy_level': '없음', 'cooking_method': '튀김+트러플소스'},
        'scores': {'taste': 88, 'price': 72, 'crispy': 78, 'popularity': 72},
    },
    # ---- 60계 ----
    {
        'brand_slug': '60gye-fried',
        'name': '후라이드',
        'slug': '60gye-fried-original',
        'description': '옛날 방식 후라이드의 정석. 가성비 최고',
        'product_type': 'fried',
        'usage': 'solo',
        'price_min': 22900,
        'price_max': 24900,
        'specs': {'price': '22900', 'calories': '1650', 'serving': '850', 'spicy_level': '없음', 'cooking_method': '튀김'},
        'scores': {'taste': 75, 'price': 95, 'crispy': 80, 'popularity': 75},
    },
    {
        'brand_slug': '60gye-fried',
        'name': '크크크치킨',
        'slug': '60gye-ccc-chicken',
        'description': '크런치 크럼블 크리스피. 콘크럼블 시즈닝이 특징',
        'product_type': 'fried',
        'usage': 'solo',
        'price_min': 23900,
        'price_max': 25900,
        'specs': {'price': '23900', 'calories': '1800', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+시즈닝'},
        'scores': {'taste': 78, 'price': 92, 'crispy': 88, 'popularity': 72},
    },
]

# ============================================================================
# 남자시계 제품 데이터
# ============================================================================
MENS_WATCH_DATA = [
    # ---- 파텍 필립 ----
    {
        'brand_slug': 'patek-philippe',
        'name': '노틸러스 5711/1A',
        'slug': 'patek-nautilus-5711-1a',
        'description': '럭셔리 스포츠워치의 아이콘. 제럴드 젠타 디자인의 걸작',
        'product_type': 'sport',
        'usage': 'collection',
        'price_min': 100000000,
        'price_max': 150000000,
        'specs': {'case_diameter': '40', 'case_thickness': '8.3', 'water_resistance': '120', 'movement': '칼리버 26-330 S C', 'power_reserve': '45', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 100, 'resale': 100, 'prestige': 100},
    },
    {
        'brand_slug': 'patek-philippe',
        'name': '칼라트라바 5227G',
        'slug': 'patek-calatrava-5227g',
        'description': '드레스워치의 정수. 클래식한 우아함의 대명사',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 45000000,
        'price_max': 55000000,
        'specs': {'case_diameter': '39', 'case_thickness': '9.2', 'water_resistance': '30', 'movement': '칼리버 324 S C', 'power_reserve': '45', 'case_material': '18K 화이트골드', 'crystal': '사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 100, 'resale': 95, 'prestige': 98},
    },
    {
        'brand_slug': 'patek-philippe',
        'name': '아쿠아넛 5167A',
        'slug': 'patek-aquanaut-5167a',
        'description': '노틸러스의 캐주얼 버전. 스포티한 럭셔리',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 70000000,
        'price_max': 90000000,
        'specs': {'case_diameter': '40', 'case_thickness': '8.1', 'water_resistance': '120', 'movement': '칼리버 324 S C', 'power_reserve': '45', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 98, 'resale': 98, 'prestige': 98},
    },
    # ---- 롤렉스 ----
    {
        'brand_slug': 'rolex',
        'name': '서브마리너 126610LN',
        'slug': 'rolex-submariner-126610ln',
        'description': '다이버워치의 기준. 결국 돌고 돌아 롤렉스',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 16500000,
        'price_max': 22000000,
        'specs': {'case_diameter': '41', 'case_thickness': '12.5', 'water_resistance': '300', 'movement': '칼리버 3235', 'power_reserve': '70', 'case_material': '오이스터스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 98, 'craftsmanship': 95, 'resale': 100, 'prestige': 98},
    },
    {
        'brand_slug': 'rolex',
        'name': '데이토나 126500LN',
        'slug': 'rolex-daytona-126500ln',
        'description': '레이싱 크로노그래프의 전설. 세라토나',
        'product_type': 'chronograph',
        'usage': 'collection',
        'price_min': 35000000,
        'price_max': 55000000,
        'specs': {'case_diameter': '40', 'case_thickness': '12.2', 'water_resistance': '100', 'movement': '칼리버 4131', 'power_reserve': '72', 'case_material': '오이스터스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 95, 'resale': 100, 'prestige': 100},
    },
    {
        'brand_slug': 'rolex',
        'name': 'GMT-마스터 II 126710BLNR',
        'slug': 'rolex-gmt-master-126710blnr',
        'description': 'GMT 기능의 완성. 배트맨이라 불리는 인기 모델',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 13500000,
        'price_max': 25000000,
        'specs': {'case_diameter': '40', 'case_thickness': '12', 'water_resistance': '100', 'movement': '칼리버 3285', 'power_reserve': '70', 'case_material': '오이스터스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 98, 'craftsmanship': 95, 'resale': 98, 'prestige': 98},
    },
    {
        'brand_slug': 'rolex',
        'name': '데이저스트 126334',
        'slug': 'rolex-datejust-126334',
        'description': '롤렉스 클래식의 정수. 41mm 모던 버전',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 12000000,
        'price_max': 16000000,
        'specs': {'case_diameter': '41', 'case_thickness': '11.8', 'water_resistance': '100', 'movement': '칼리버 3235', 'power_reserve': '70', 'case_material': '오이스터스틸+화이트골드', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 92, 'resale': 92, 'prestige': 95},
    },
    # ---- 오데마 피게 ----
    {
        'brand_slug': 'audemars-piguet',
        'name': '로열오크 15500ST',
        'slug': 'ap-royal-oak-15500st',
        'description': '럭셔리 스포츠워치의 창시자. 제럴드 젠타의 걸작',
        'product_type': 'sport',
        'usage': 'collection',
        'price_min': 45000000,
        'price_max': 60000000,
        'specs': {'case_diameter': '41', 'case_thickness': '10.4', 'water_resistance': '50', 'movement': '칼리버 4302', 'power_reserve': '70', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 98, 'craftsmanship': 100, 'resale': 98, 'prestige': 100},
    },
    {
        'brand_slug': 'audemars-piguet',
        'name': '로열오크 오프쇼어 26470ST',
        'slug': 'ap-royal-oak-offshore-26470st',
        'description': '더 크고 강한 로열오크. 스포츠 크로노그래프',
        'product_type': 'chronograph',
        'usage': 'sport',
        'price_min': 55000000,
        'price_max': 70000000,
        'specs': {'case_diameter': '42', 'case_thickness': '14.2', 'water_resistance': '100', 'movement': '칼리버 3126/3840', 'power_reserve': '50', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 98, 'resale': 95, 'prestige': 98},
    },
    # ---- 오메가 ----
    {
        'brand_slug': 'omega',
        'name': '스피드마스터 문워치 프로',
        'slug': 'omega-speedmaster-moonwatch-pro',
        'description': '달에 간 시계. NASA 공인 우주 시계',
        'product_type': 'chronograph',
        'usage': 'casual',
        'price_min': 9500000,
        'price_max': 11000000,
        'specs': {'case_diameter': '42', 'case_thickness': '13.2', 'water_resistance': '50', 'movement': '칼리버 3861', 'power_reserve': '50', 'case_material': '스테인리스 스틸', 'crystal': '헤잘라이트/사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 92, 'resale': 85, 'prestige': 95},
    },
    {
        'brand_slug': 'omega',
        'name': '씨마스터 300M 다이버',
        'slug': 'omega-seamaster-300m',
        'description': '제임스 본드의 시계. 세라믹 베젤의 프로 다이버',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 7500000,
        'price_max': 9000000,
        'specs': {'case_diameter': '42', 'case_thickness': '13.6', 'water_resistance': '300', 'movement': '칼리버 8800', 'power_reserve': '55', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 92, 'resale': 82, 'prestige': 90},
    },
    {
        'brand_slug': 'omega',
        'name': '아쿠아 테라 150M',
        'slug': 'omega-aqua-terra-150m',
        'description': '비즈니스와 스포츠의 완벽한 조화',
        'product_type': 'sport',
        'usage': 'formal',
        'price_min': 8500000,
        'price_max': 10500000,
        'specs': {'case_diameter': '41', 'case_thickness': '13.2', 'water_resistance': '150', 'movement': '칼리버 8900', 'power_reserve': '60', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 92, 'craftsmanship': 92, 'resale': 80, 'prestige': 88},
    },
    # ---- 태그호이어 ----
    {
        'brand_slug': 'tag-heuer',
        'name': '카레라 크로노그래프',
        'slug': 'tag-heuer-carrera-chrono',
        'description': '모터스포츠 헤리티지. 클래식 레이싱 크로노그래프',
        'product_type': 'chronograph',
        'usage': 'casual',
        'price_min': 6000000,
        'price_max': 8000000,
        'specs': {'case_diameter': '44', 'case_thickness': '14.5', 'water_resistance': '100', 'movement': '칼리버 TH20-00', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 90, 'craftsmanship': 82, 'resale': 70, 'prestige': 82},
    },
    {
        'brand_slug': 'tag-heuer',
        'name': '모나코',
        'slug': 'tag-heuer-monaco',
        'description': '스티브 맥퀸의 시계. 세계 최초 사각 자동 크로노',
        'product_type': 'chronograph',
        'usage': 'casual',
        'price_min': 8000000,
        'price_max': 10000000,
        'specs': {'case_diameter': '39', 'case_thickness': '14', 'water_resistance': '100', 'movement': '칼리버 11', 'power_reserve': '40', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 82, 'resale': 75, 'prestige': 88},
    },
    {
        'brand_slug': 'tag-heuer',
        'name': '아쿠아레이서 300',
        'slug': 'tag-heuer-aquaracer-300',
        'description': '다이버 워치의 새로운 기준. 세라믹 베젤 적용',
        'product_type': 'diver',
        'usage': 'sport',
        'price_min': 4500000,
        'price_max': 6000000,
        'specs': {'case_diameter': '42', 'case_thickness': '12', 'water_resistance': '300', 'movement': '칼리버 TH30', 'power_reserve': '60', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 80, 'resale': 68, 'prestige': 78},
    },
    # ---- IWC ----
    {
        'brand_slug': 'iwc',
        'name': '빅 파일럿 43',
        'slug': 'iwc-big-pilot-43',
        'description': '파일럿 워치의 대명사. 역사적 항법 기구의 현대적 해석',
        'product_type': 'pilot',
        'usage': 'casual',
        'price_min': 12000000,
        'price_max': 15000000,
        'specs': {'case_diameter': '43', 'case_thickness': '13.6', 'water_resistance': '100', 'movement': '칼리버 82100', 'power_reserve': '60', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 92, 'resale': 82, 'prestige': 90},
    },
    {
        'brand_slug': 'iwc',
        'name': '포르투기스 크로노',
        'slug': 'iwc-portugieser-chrono',
        'description': '항해 시계의 우아함. IWC의 스테디셀러',
        'product_type': 'chronograph',
        'usage': 'formal',
        'price_min': 9700000,
        'price_max': 12000000,
        'specs': {'case_diameter': '41', 'case_thickness': '13.5', 'water_resistance': '30', 'movement': '칼리버 69355', 'power_reserve': '46', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 92, 'craftsmanship': 92, 'resale': 80, 'prestige': 88},
    },
    # ---- 그랜드 세이코 ----
    {
        'brand_slug': 'grand-seiko',
        'name': 'SBGA211 스노우플레이크',
        'slug': 'grand-seiko-sbga211',
        'description': '설경 다이얼의 아름다움. 스프링 드라이브의 정수',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 8400000,
        'price_max': 9500000,
        'specs': {'case_diameter': '41', 'case_thickness': '12.3', 'water_resistance': '100', 'movement': '스프링 드라이브 9R65', 'power_reserve': '72', 'case_material': '하이인텐시티 티타늄', 'crystal': '사파이어'},
        'scores': {'heritage': 88, 'craftsmanship': 98, 'resale': 75, 'prestige': 88},
    },
    {
        'brand_slug': 'grand-seiko',
        'name': 'SBGW285 엘레강스',
        'slug': 'grand-seiko-sbgw285',
        'description': '수동 와인딩의 정수. 심플한 우아함',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 5200000,
        'price_max': 6000000,
        'specs': {'case_diameter': '37.3', 'case_thickness': '10.3', 'water_resistance': '30', 'movement': '9S64', 'power_reserve': '72', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 95, 'resale': 70, 'prestige': 82},
    },
    # ---- 튜더 ----
    {
        'brand_slug': 'tudor',
        'name': '블랙 베이 58',
        'slug': 'tudor-black-bay-58',
        'description': '롤렉스의 동생. 가성비 최고의 럭셔리 다이버',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 5200000,
        'price_max': 6000000,
        'specs': {'case_diameter': '39', 'case_thickness': '11.9', 'water_resistance': '200', 'movement': 'MT5402', 'power_reserve': '70', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 85, 'resale': 78, 'prestige': 82},
    },
    {
        'brand_slug': 'tudor',
        'name': '펠라고스 FXD',
        'slug': 'tudor-pelagos-fxd',
        'description': '밀리터리 스펙 다이버. 티타늄 케이스의 프로 도구',
        'product_type': 'diver',
        'usage': 'sport',
        'price_min': 6000000,
        'price_max': 7000000,
        'specs': {'case_diameter': '42', 'case_thickness': '12.3', 'water_resistance': '200', 'movement': 'MT5602', 'power_reserve': '70', 'case_material': '티타늄', 'crystal': '사파이어'},
        'scores': {'heritage': 82, 'craftsmanship': 88, 'resale': 75, 'prestige': 80},
    },
    # ---- 티쏘 ----
    {
        'brand_slug': 'tissot',
        'name': 'PRX 파워매틱 80',
        'slug': 'tissot-prx-powermatic-80',
        'description': '70년대 레트로 디자인의 부활. 가성비 럭셔리 스포츠워치',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 850000,
        'price_max': 960000,
        'specs': {'case_diameter': '40', 'case_thickness': '10.9', 'water_resistance': '100', 'movement': '파워매틱 80.111', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 78, 'craftsmanship': 75, 'resale': 55, 'prestige': 68},
    },
    {
        'brand_slug': 'tissot',
        'name': '젠틀맨 파워매틱 80',
        'slug': 'tissot-gentleman-powermatic-80',
        'description': '비즈니스 캐주얼의 정석. 깔끔한 드레스워치',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 900000,
        'price_max': 1100000,
        'specs': {'case_diameter': '40', 'case_thickness': '11', 'water_resistance': '100', 'movement': '파워매틱 80.111', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 78, 'craftsmanship': 75, 'resale': 50, 'prestige': 65},
    },
    # ---- 해밀턴 ----
    {
        'brand_slug': 'hamilton',
        'name': '카키 필드 오토매틱 38',
        'slug': 'hamilton-khaki-field-38',
        'description': '밀리터리 필드워치의 전설. 영화 속 단골 시계',
        'product_type': 'pilot',
        'usage': 'casual',
        'price_min': 750000,
        'price_max': 900000,
        'specs': {'case_diameter': '38', 'case_thickness': '9.5', 'water_resistance': '100', 'movement': 'H-10', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 72, 'resale': 50, 'prestige': 65},
    },
    {
        'brand_slug': 'hamilton',
        'name': '벤츄라 오토매틱',
        'slug': 'hamilton-ventura-auto',
        'description': '엘비스 프레슬리의 시계. 세계 최초 전기 시계의 디자인',
        'product_type': 'dress',
        'usage': 'casual',
        'price_min': 1200000,
        'price_max': 1500000,
        'specs': {'case_diameter': '42.5', 'case_thickness': '12.1', 'water_resistance': '50', 'movement': 'H-10', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 90, 'craftsmanship': 70, 'resale': 48, 'prestige': 68},
    },
    # ---- 세이코 ----
    {
        'brand_slug': 'seiko',
        'name': 'SKX007',
        'slug': 'seiko-skx007',
        'description': '전설의 가성비 다이버. 모딩의 바이블 (단종)',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 400000,
        'price_max': 600000,
        'specs': {'case_diameter': '42', 'case_thickness': '13.4', 'water_resistance': '200', 'movement': '7S26', 'power_reserve': '41', 'case_material': '스테인리스 스틸', 'crystal': '하드렉스'},
        'scores': {'heritage': 88, 'craftsmanship': 72, 'resale': 55, 'prestige': 65},
    },
    {
        'brand_slug': 'seiko',
        'name': '프레사지 샤프엣지',
        'slug': 'seiko-presage-sharp-edged',
        'description': '일본 전통미와 현대적 디자인의 조화',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 600000,
        'price_max': 800000,
        'specs': {'case_diameter': '39.3', 'case_thickness': '11.1', 'water_resistance': '100', 'movement': '6R35', 'power_reserve': '70', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 82, 'craftsmanship': 78, 'resale': 45, 'prestige': 62},
    },
    # ---- 카시오 / 지샥 ----
    {
        'brand_slug': 'casio-gshock',
        'name': 'G-SHOCK GA-2100',
        'slug': 'gshock-ga-2100',
        'description': '카시오크라 불리는 인기 모델. 슬림한 지샥',
        'product_type': 'sport',
        'usage': 'sport',
        'price_min': 120000,
        'price_max': 180000,
        'specs': {'case_diameter': '45.4', 'case_thickness': '11.8', 'water_resistance': '200', 'movement': '쿼츠 5611', 'power_reserve': '배터리 3년', 'case_material': '카본코어 수지', 'crystal': '미네랄'},
        'scores': {'heritage': 75, 'craftsmanship': 80, 'resale': 35, 'prestige': 55},
    },
    {
        'brand_slug': 'casio-gshock',
        'name': 'G-SHOCK GMW-B5000',
        'slug': 'gshock-gmw-b5000',
        'description': '오리지널 스퀘어 지샥의 풀메탈 버전',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 550000,
        'price_max': 700000,
        'specs': {'case_diameter': '43.2', 'case_thickness': '13', 'water_resistance': '200', 'movement': '터프솔라', 'power_reserve': '솔라', 'case_material': '스테인리스 스틸', 'crystal': '미네랄'},
        'scores': {'heritage': 80, 'craftsmanship': 82, 'resale': 40, 'prestige': 58},
    },
]


class Command(BaseCommand):
    help = '제품(모델) 시드 데이터 생성'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='기존 제품 데이터 삭제 후 재생성',
        )
        parser.add_argument(
            '--category',
            type=str,
            help='특정 카테고리만 생성 (running-shoes, chicken, mens-watch)',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write('기존 제품 데이터 삭제 중...')
            ProductScore.objects.all().delete()
            ProductSpec.objects.all().delete()
            Product.objects.all().delete()

        category_filter = options.get('category')

        # 카테고리별 데이터 처리
        data_map = {
            'running-shoes': RUNNING_SHOES_DATA,
            'chicken': CHICKEN_DATA,
            'mens-watch': MENS_WATCH_DATA,
        }

        for cat_slug, products in data_map.items():
            if category_filter and category_filter != cat_slug:
                continue

            try:
                category = Category.objects.get(slug=cat_slug)
            except Category.DoesNotExist:
                self.stdout.write(
                    self.style.WARNING(f'카테고리 {cat_slug}를 찾을 수 없음. seed_categories 먼저 실행 필요')
                )
                continue

            self.stdout.write(f'\n{category.icon} {category.name} 제품 생성 중...')

            for product_data in products:
                brand_slug = product_data.pop('brand_slug')
                specs_data = product_data.pop('specs', {})
                scores_data = product_data.pop('scores', {})

                try:
                    brand = Brand.objects.get(slug=brand_slug)
                except Brand.DoesNotExist:
                    self.stdout.write(
                        self.style.WARNING(f'  브랜드 {brand_slug}를 찾을 수 없음. 스킵')
                    )
                    continue

                # 제품 생성/업데이트
                product, created = Product.objects.update_or_create(
                    slug=product_data['slug'],
                    defaults={
                        'brand': brand,
                        'category': category,
                        'name': product_data['name'],
                        'description': product_data.get('description', ''),
                        'product_type': product_data.get('product_type', ''),
                        'usage': product_data.get('usage', ''),
                        'price_min': product_data.get('price_min', 0),
                        'price_max': product_data.get('price_max', 0),
                        'release_year': product_data.get('release_year'),
                        'version_number': product_data.get('version_number', 1),
                    }
                )

                # 스펙 생성/업데이트
                for key, value in specs_data.items():
                    ProductSpec.objects.update_or_create(
                        product=product,
                        key=key,
                        defaults={'value': str(value)}
                    )

                # 점수 생성/업데이트 및 티어 점수 계산
                total_score = 0
                total_weight = 0
                score_defs = category.score_definitions or []

                for key, value in scores_data.items():
                    ProductScore.objects.update_or_create(
                        product=product,
                        key=key,
                        defaults={'value': float(value)}
                    )
                    # 가중치 점수 계산
                    for d in score_defs:
                        if d.get('key') == key:
                            weight = d.get('weight', 0)
                            total_score += float(value) * weight
                            total_weight += weight
                            break

                # 티어 점수 업데이트
                if total_weight > 0:
                    product.tier_score = total_score / total_weight
                    product.save()

                action = '생성' if created else '업데이트'
                self.stdout.write(
                    f'  {product.tier}티어 {product.name} {action} (점수: {product.tier_score:.1f})'
                )

        self.stdout.write(self.style.SUCCESS('\n제품 시드 데이터 생성 완료!'))
        self.stdout.write(f'  총 제품 수: {Product.objects.count()}개')
        self.stdout.write(f'  제품 스펙: {ProductSpec.objects.count()}개')
        self.stdout.write(f'  제품 점수: {ProductScore.objects.count()}개')
