"""
제품 시드 데이터 생성 커맨드.
사용: python manage.py seed_products
"""
from django.core.management.base import BaseCommand
from brands.models import Category, Brand
from models_app.models import Product, ProductSpec, ProductScore


# ============================================================================
# 러닝화 제품 데이터
# ============================================================================
RUNNING_SHOES_DATA = [
    # ---- 나이키 ----
    {
        'brand_slug': 'nike',
        'name': 'Vaporfly 3',
        'slug': 'nike-vaporfly-3',
        'description': '나이키 최고의 레이싱 슈즈. ZoomX 폼과 풀렝스 카본 플레이트로 최상의 에너지 리턴 제공',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 310000,
        'release_year': 2023,
        'version_number': 3,
        'specs': {'weight': '188', 'stack_height': '40', 'drop': '8', 'upper': '플라이니트', 'midsole': 'ZoomX + 카본 플레이트'},
        'scores': {'cushion': 95, 'responsiveness': 98, 'stability': 75, 'durability': 70},
    },
    {
        'brand_slug': 'nike',
        'name': 'Alphafly 3',
        'slug': 'nike-alphafly-3',
        'description': '킵초게가 세계기록을 세운 슈즈의 후속작. 에어줌 유닛과 카본 플레이트 조합',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 350000,
        'price_max': 380000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '212', 'stack_height': '40', 'drop': '4', 'upper': '아토미니트', 'midsole': 'ZoomX + Air Zoom + 카본'},
        'scores': {'cushion': 98, 'responsiveness': 96, 'stability': 72, 'durability': 68},
    },
    {
        'brand_slug': 'nike',
        'name': 'Pegasus 41',
        'slug': 'nike-pegasus-41',
        'description': '나이키 대표 데일리 트레이너. 40년 역사의 검증된 라인업',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 149000,
        'price_max': 169000,
        'release_year': 2024,
        'version_number': 41,
        'specs': {'weight': '272', 'stack_height': '28', 'drop': '10', 'upper': '메쉬', 'midsole': 'React X'},
        'scores': {'cushion': 85, 'responsiveness': 78, 'stability': 82, 'durability': 85},
    },
    {
        'brand_slug': 'nike',
        'name': 'Structure 26',
        'slug': 'nike-structure-26',
        'description': '안정화 러닝화의 기준. 내측 지지대로 오버프로네이션 방지',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 139000,
        'price_max': 159000,
        'release_year': 2024,
        'version_number': 26,
        'specs': {'weight': '285', 'stack_height': '26', 'drop': '10', 'upper': '메쉬', 'midsole': 'React X + 미드풋 지지대'},
        'scores': {'cushion': 80, 'responsiveness': 72, 'stability': 92, 'durability': 85},
    },
    # ---- 아식스 ----
    {
        'brand_slug': 'asics',
        'name': 'Metaspeed Sky+',
        'slug': 'asics-metaspeed-sky-plus',
        'description': '스트라이드 러너를 위한 레이싱 슈즈. FF BLAST TURBO와 카본 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 290000,
        'price_max': 320000,
        'release_year': 2023,
        'version_number': 2,
        'specs': {'weight': '195', 'stack_height': '38', 'drop': '5', 'upper': '모션랩 어퍼', 'midsole': 'FF BLAST TURBO + 카본'},
        'scores': {'cushion': 90, 'responsiveness': 94, 'stability': 80, 'durability': 75},
    },
    {
        'brand_slug': 'asics',
        'name': 'Metaspeed Edge+',
        'slug': 'asics-metaspeed-edge-plus',
        'description': '케이던스 러너를 위한 레이싱 슈즈. 빠른 회전율에 최적화',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 290000,
        'price_max': 320000,
        'release_year': 2023,
        'version_number': 2,
        'specs': {'weight': '190', 'stack_height': '33', 'drop': '5', 'upper': '모션랩 어퍼', 'midsole': 'FF BLAST TURBO + 카본'},
        'scores': {'cushion': 85, 'responsiveness': 96, 'stability': 82, 'durability': 74},
    },
    {
        'brand_slug': 'asics',
        'name': 'Gel Nimbus 26',
        'slug': 'asics-gel-nimbus-26',
        'description': '아식스 프리미엄 쿠션화. GEL 기술과 FF BLAST PLUS로 최상의 편안함',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 189000,
        'price_max': 210000,
        'release_year': 2024,
        'version_number': 26,
        'specs': {'weight': '290', 'stack_height': '35', 'drop': '8', 'upper': '엔지니어드 메쉬', 'midsole': 'FF BLAST PLUS + GEL'},
        'scores': {'cushion': 92, 'responsiveness': 72, 'stability': 85, 'durability': 88},
    },
    {
        'brand_slug': 'asics',
        'name': 'Gel Kayano 31',
        'slug': 'asics-gel-kayano-31',
        'description': '30년 역사의 안정화 명가. 4D 가이드 시스템으로 완벽한 지지력',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 199000,
        'price_max': 220000,
        'release_year': 2024,
        'version_number': 31,
        'specs': {'weight': '305', 'stack_height': '35', 'drop': '10', 'upper': '엔지니어드 메쉬', 'midsole': 'FF BLAST PLUS + 4D 가이드'},
        'scores': {'cushion': 88, 'responsiveness': 70, 'stability': 95, 'durability': 90},
    },
    {
        'brand_slug': 'asics',
        'name': 'Novablast 5',
        'slug': 'asics-novablast-5',
        'description': '경쾌한 반발력의 데일리 트레이너. FF BLAST PLUS 폼의 탄성',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 5,
        'specs': {'weight': '255', 'stack_height': '32', 'drop': '8', 'upper': '메쉬', 'midsole': 'FF BLAST PLUS'},
        'scores': {'cushion': 86, 'responsiveness': 85, 'stability': 75, 'durability': 82},
    },
    # ---- 호카 ----
    {
        'brand_slug': 'hoka',
        'name': 'Rocket X2',
        'slug': 'hoka-rocket-x2',
        'description': '호카의 레이싱 슈퍼슈즈. PEBA 폼과 카본 플레이트 조합',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2023,
        'version_number': 2,
        'specs': {'weight': '205', 'stack_height': '38', 'drop': '5', 'upper': '크릴 메쉬', 'midsole': 'PEBA + 카본 플레이트'},
        'scores': {'cushion': 88, 'responsiveness': 90, 'stability': 78, 'durability': 75},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Cielo X1',
        'slug': 'hoka-cielo-x1',
        'description': '호카의 최신 카본 레이서. 빠른 러너를 위한 최경량 설계',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 300000,
        'price_max': 330000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '178', 'stack_height': '39', 'drop': '5', 'upper': '크릴 메쉬', 'midsole': 'PEBA + 카본 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 94, 'stability': 75, 'durability': 72},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Clifton 9',
        'slug': 'hoka-clifton-9',
        'description': '호카 대표 데일리 트레이너. 맥시멀 쿠셔닝의 정석',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2023,
        'version_number': 9,
        'specs': {'weight': '248', 'stack_height': '32', 'drop': '5', 'upper': '엔지니어드 메쉬', 'midsole': 'CMEVA'},
        'scores': {'cushion': 90, 'responsiveness': 75, 'stability': 80, 'durability': 82},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Bondi 8',
        'slug': 'hoka-bondi-8',
        'description': '호카 최고의 쿠셔닝. 장거리 러닝에 최적화된 맥시멀 쿠션',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2023,
        'version_number': 8,
        'specs': {'weight': '307', 'stack_height': '37', 'drop': '4', 'upper': '엔지니어드 메쉬', 'midsole': 'CMEVA'},
        'scores': {'cushion': 95, 'responsiveness': 68, 'stability': 78, 'durability': 85},
    },
    {
        'brand_slug': 'hoka',
        'name': 'Mach 6',
        'slug': 'hoka-mach-6',
        'description': '템포런에 최적화된 경량 트레이너. PEBA 폼 적용',
        'product_type': 'speed',
        'usage': 'tempo',
        'price_min': 169000,
        'price_max': 189000,
        'release_year': 2024,
        'version_number': 6,
        'specs': {'weight': '232', 'stack_height': '32', 'drop': '5', 'upper': '엔지니어드 메쉬', 'midsole': 'PEBA'},
        'scores': {'cushion': 82, 'responsiveness': 88, 'stability': 78, 'durability': 78},
    },
    # ---- 뉴발란스 ----
    {
        'brand_slug': 'new-balance',
        'name': 'SC Elite v4',
        'slug': 'new-balance-sc-elite-v4',
        'description': '뉴발란스 플래그십 레이서. FuelCell 슈퍼컴프 엘리트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 320000,
        'price_max': 350000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '198', 'stack_height': '38', 'drop': '8', 'upper': '뉴메쉬', 'midsole': 'FuelCell + 카본 플레이트'},
        'scores': {'cushion': 92, 'responsiveness': 93, 'stability': 76, 'durability': 72},
    },
    {
        'brand_slug': 'new-balance',
        'name': 'FuelCell Rebel v4',
        'slug': 'new-balance-fuelcell-rebel-v4',
        'description': '템포런과 데일리 트레이닝에 최적. 경쾌한 반발력',
        'product_type': 'cushion',
        'usage': 'tempo',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '228', 'stack_height': '30', 'drop': '6', 'upper': '메쉬', 'midsole': 'FuelCell'},
        'scores': {'cushion': 85, 'responsiveness': 88, 'stability': 78, 'durability': 80},
    },
    {
        'brand_slug': 'new-balance',
        'name': 'Fresh Foam 1080v13',
        'slug': 'new-balance-fresh-foam-1080-v13',
        'description': '뉴발란스 프리미엄 데일리 트레이너. Fresh Foam X 적용',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2023,
        'version_number': 13,
        'specs': {'weight': '280', 'stack_height': '34', 'drop': '6', 'upper': '하이포니트', 'midsole': 'Fresh Foam X'},
        'scores': {'cushion': 90, 'responsiveness': 75, 'stability': 82, 'durability': 85},
    },
    {
        'brand_slug': 'new-balance',
        'name': 'Fresh Foam 860v14',
        'slug': 'new-balance-fresh-foam-860-v14',
        'description': '안정화 데일리 트레이너. 내측 포스팅으로 오버프로네이션 지원',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 169000,
        'price_max': 189000,
        'release_year': 2024,
        'version_number': 14,
        'specs': {'weight': '295', 'stack_height': '32', 'drop': '10', 'upper': '메쉬', 'midsole': 'Fresh Foam X + 포스팅'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 90, 'durability': 86},
    },
    # ---- 아디다스 ----
    {
        'brand_slug': 'adidas',
        'name': 'Adizero Adios Pro 3',
        'slug': 'adidas-adizero-adios-pro-3',
        'description': '아디다스 플래그십 레이서. 라이트스트라이크 프로와 에너지 로드',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 300000,
        'price_max': 330000,
        'release_year': 2023,
        'version_number': 3,
        'specs': {'weight': '215', 'stack_height': '39', 'drop': '6.5', 'upper': '라이트웨이트 메쉬', 'midsole': 'Lightstrike Pro + 에너지 로드'},
        'scores': {'cushion': 92, 'responsiveness': 95, 'stability': 78, 'durability': 72},
    },
    {
        'brand_slug': 'adidas',
        'name': 'Adizero Boston 12',
        'slug': 'adidas-adizero-boston-12',
        'description': '템포런에 최적화된 트레이너. 에너지 로드 2.0 적용',
        'product_type': 'cushion',
        'usage': 'tempo',
        'price_min': 180000,
        'price_max': 200000,
        'release_year': 2024,
        'version_number': 12,
        'specs': {'weight': '235', 'stack_height': '33', 'drop': '6.5', 'upper': '엔지니어드 메쉬', 'midsole': 'Lightstrike Pro + 에너지 로드 2.0'},
        'scores': {'cushion': 82, 'responsiveness': 88, 'stability': 85, 'durability': 80},
    },
    {
        'brand_slug': 'adidas',
        'name': 'Ultraboost Light',
        'slug': 'adidas-ultraboost-light',
        'description': '아디다스 아이코닉 데일리 러너. 라이트 부스트 적용으로 경량화',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 199000,
        'price_max': 230000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '275', 'stack_height': '29', 'drop': '10', 'upper': '프라임니트', 'midsole': 'Light Boost'},
        'scores': {'cushion': 88, 'responsiveness': 78, 'stability': 80, 'durability': 82},
    },
    {
        'brand_slug': 'adidas',
        'name': 'Supernova Rise',
        'slug': 'adidas-supernova-rise',
        'description': '입문자용 데일리 트레이너. 드림스트라이크+ 폼 적용',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 139000,
        'price_max': 159000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '295', 'stack_height': '30', 'drop': '10', 'upper': '메쉬', 'midsole': 'Dreamstrike+'},
        'scores': {'cushion': 82, 'responsiveness': 72, 'stability': 85, 'durability': 88},
    },
    # ---- 써코니 ----
    {
        'brand_slug': 'saucony',
        'name': 'Endorphin Pro 4',
        'slug': 'saucony-endorphin-pro-4',
        'description': '써코니 플래그십 레이서. 파워런 PB와 카본 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '195', 'stack_height': '38', 'drop': '8', 'upper': '슬림 메쉬', 'midsole': 'PWRRUN PB + 카본 플레이트'},
        'scores': {'cushion': 90, 'responsiveness': 94, 'stability': 76, 'durability': 72},
    },
    {
        'brand_slug': 'saucony',
        'name': 'Endorphin Speed 4',
        'slug': 'saucony-endorphin-speed-4',
        'description': '템포와 레이스 겸용. 나일론 플레이트로 안정적인 추진력',
        'product_type': 'speed',
        'usage': 'tempo',
        'price_min': 200000,
        'price_max': 220000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '215', 'stack_height': '36', 'drop': '8', 'upper': '메쉬', 'midsole': 'PWRRUN PB + 나일론 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 90, 'stability': 82, 'durability': 78},
    },
    {
        'brand_slug': 'saucony',
        'name': 'Triumph 22',
        'slug': 'saucony-triumph-22',
        'description': '써코니 프리미엄 데일리 트레이너. PWRRUN+ 쿠셔닝',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2024,
        'version_number': 22,
        'specs': {'weight': '283', 'stack_height': '32', 'drop': '10', 'upper': 'FORMFIT', 'midsole': 'PWRRUN+'},
        'scores': {'cushion': 92, 'responsiveness': 75, 'stability': 82, 'durability': 85},
    },
    {
        'brand_slug': 'saucony',
        'name': 'Guide 17',
        'slug': 'saucony-guide-17',
        'description': '안정화 러너의 선택. 내측 지지대로 과회전 방지',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 17,
        'specs': {'weight': '275', 'stack_height': '30', 'drop': '8', 'upper': 'FORMFIT', 'midsole': 'PWRRUN + 내측 지지대'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 90, 'durability': 85},
    },
    # ---- 브룩스 ----
    {
        'brand_slug': 'brooks',
        'name': 'Hyperion Elite 4',
        'slug': 'brooks-hyperion-elite-4',
        'description': '브룩스 레이싱 슈퍼슈즈. DNA FLASH와 카본 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2024,
        'version_number': 4,
        'specs': {'weight': '198', 'stack_height': '36', 'drop': '8', 'upper': '라이트웨이트 어퍼', 'midsole': 'DNA FLASH + 카본 플레이트'},
        'scores': {'cushion': 88, 'responsiveness': 92, 'stability': 78, 'durability': 72},
    },
    {
        'brand_slug': 'brooks',
        'name': 'Glycerin 21',
        'slug': 'brooks-glycerin-21',
        'description': '브룩스 최고의 쿠셔닝. DNA LOFT v3로 부드러운 착지감',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 189000,
        'price_max': 210000,
        'release_year': 2024,
        'version_number': 21,
        'specs': {'weight': '290', 'stack_height': '34', 'drop': '10', 'upper': '엔지니어드 메쉬', 'midsole': 'DNA LOFT v3'},
        'scores': {'cushion': 95, 'responsiveness': 72, 'stability': 80, 'durability': 88},
    },
    {
        'brand_slug': 'brooks',
        'name': 'Ghost 16',
        'slug': 'brooks-ghost-16',
        'description': '브룩스 베스트셀러 데일리 트레이너. 균형잡힌 쿠셔닝',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 149000,
        'price_max': 169000,
        'release_year': 2024,
        'version_number': 16,
        'specs': {'weight': '278', 'stack_height': '32', 'drop': '12', 'upper': '메쉬', 'midsole': 'DNA LOFT'},
        'scores': {'cushion': 88, 'responsiveness': 75, 'stability': 82, 'durability': 88},
    },
    {
        'brand_slug': 'brooks',
        'name': 'Adrenaline GTS 24',
        'slug': 'brooks-adrenaline-gts-24',
        'description': '안정화의 기준. GuideRails로 발의 움직임 제어',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 24,
        'specs': {'weight': '285', 'stack_height': '32', 'drop': '12', 'upper': '메쉬', 'midsole': 'DNA LOFT + GuideRails'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 92, 'durability': 88},
    },
    # ---- 푸마 ----
    {
        'brand_slug': 'puma',
        'name': 'Deviate Nitro Elite 4',
        'slug': 'puma-deviate-nitro-elite-4',
        'description': '푸마 플래그십 레이서. 170g 초경량 카본 슈퍼슈즈',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2026,
        'version_number': 4,
        'specs': {'weight': '170', 'stack_height': '38', 'drop': '7', 'upper': '울트라 라이트 메쉬', 'midsole': 'NITROFOAM Elite + 카본'},
        'scores': {'cushion': 85, 'responsiveness': 95, 'stability': 75, 'durability': 70},
    },
    {
        'brand_slug': 'puma',
        'name': 'Deviate Nitro 4',
        'slug': 'puma-deviate-nitro-4',
        'description': '템포와 대회 겸용 트레이너. 듀얼 레이어 나이트로폼',
        'product_type': 'speed',
        'usage': 'tempo',
        'price_min': 180000,
        'price_max': 200000,
        'release_year': 2026,
        'version_number': 4,
        'specs': {'weight': '225', 'stack_height': '35', 'drop': '7', 'upper': '엔지니어드 니트', 'midsole': 'NITROFOAM + PWRPLATE'},
        'scores': {'cushion': 85, 'responsiveness': 88, 'stability': 82, 'durability': 78},
    },
    {
        'brand_slug': 'puma',
        'name': 'Velocity Nitro 3',
        'slug': 'puma-velocity-nitro-3',
        'description': '푸마 데일리 트레이너. 가성비 뛰어난 나이트로 폼',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 139000,
        'price_max': 159000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '265', 'stack_height': '30', 'drop': '10', 'upper': '메쉬', 'midsole': 'NITROFOAM'},
        'scores': {'cushion': 82, 'responsiveness': 78, 'stability': 80, 'durability': 85},
    },
    # ---- 온러닝 ----
    {
        'brand_slug': 'on-running',
        'name': 'Cloudboom Strike',
        'slug': 'on-cloudboom-strike',
        'description': '온러닝 레이싱 슈즈. Helion HF와 Speedboard',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 290000,
        'price_max': 320000,
        'release_year': 2024,
        'version_number': 1,
        'specs': {'weight': '215', 'stack_height': '38', 'drop': '9', 'upper': '엔지니어드 메쉬', 'midsole': 'Helion HF + Speedboard'},
        'scores': {'cushion': 85, 'responsiveness': 90, 'stability': 78, 'durability': 75},
    },
    {
        'brand_slug': 'on-running',
        'name': 'Cloudmonster 2',
        'slug': 'on-cloudmonster-2',
        'description': '온러닝 맥시멀 쿠셔닝. CloudTec 구조의 독특한 착지감',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 199000,
        'price_max': 219000,
        'release_year': 2024,
        'version_number': 2,
        'specs': {'weight': '295', 'stack_height': '35', 'drop': '6', 'upper': '엔지니어드 메쉬', 'midsole': 'Helion + CloudTec'},
        'scores': {'cushion': 90, 'responsiveness': 80, 'stability': 78, 'durability': 80},
    },
    {
        'brand_slug': 'on-running',
        'name': 'Cloudstratus 3',
        'slug': 'on-cloudstratus-3',
        'description': '온러닝 안정화 쿠션. 더블 레이어 CloudTec으로 지지력 강화',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '310', 'stack_height': '32', 'drop': '6', 'upper': '엔지니어드 메쉬', 'midsole': 'Helion + 더블 CloudTec'},
        'scores': {'cushion': 88, 'responsiveness': 75, 'stability': 88, 'durability': 82},
    },
    {
        'brand_slug': 'on-running',
        'name': 'Cloudsurfer 7',
        'slug': 'on-cloudsurfer-7',
        'description': '온러닝 데일리 트레이너. 경쾌한 반응성과 쿠셔닝 밸런스',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 169000,
        'price_max': 189000,
        'release_year': 2024,
        'version_number': 7,
        'specs': {'weight': '280', 'stack_height': '29', 'drop': '10', 'upper': '메쉬', 'midsole': 'Helion + CloudTec'},
        'scores': {'cushion': 85, 'responsiveness': 82, 'stability': 80, 'durability': 82},
    },
    # ---- 미즈노 ----
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Rebellion Pro 3',
        'slug': 'mizuno-wave-rebellion-pro-3',
        'description': '미즈노 레이싱 슈퍼슈즈. 미즈노 에너지와 G3 플레이트',
        'product_type': 'speed',
        'usage': 'race',
        'price_min': 280000,
        'price_max': 300000,
        'release_year': 2024,
        'version_number': 3,
        'specs': {'weight': '200', 'stack_height': '40', 'drop': '4', 'upper': '엔지니어드 메쉬', 'midsole': '미즈노 에너지 + G3 플레이트'},
        'scores': {'cushion': 88, 'responsiveness': 92, 'stability': 78, 'durability': 72},
    },
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Rider 28',
        'slug': 'mizuno-wave-rider-28',
        'description': '미즈노 대표 데일리 트레이너. 웨이브 플레이트로 안정성 확보',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 149000,
        'price_max': 169000,
        'release_year': 2024,
        'version_number': 28,
        'specs': {'weight': '275', 'stack_height': '32', 'drop': '12', 'upper': '에어메쉬', 'midsole': '미즈노 에너지 + 웨이브 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 78, 'stability': 85, 'durability': 88},
    },
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Sky 8',
        'slug': 'mizuno-wave-sky-8',
        'description': '미즈노 프리미엄 쿠션화. 최대 쿠셔닝으로 장거리에 최적',
        'product_type': 'cushion',
        'usage': 'daily',
        'price_min': 179000,
        'price_max': 199000,
        'release_year': 2024,
        'version_number': 8,
        'specs': {'weight': '310', 'stack_height': '35', 'drop': '10', 'upper': '엔지니어드 메쉬', 'midsole': '미즈노 에너지 + 웨이브 플레이트'},
        'scores': {'cushion': 92, 'responsiveness': 70, 'stability': 82, 'durability': 86},
    },
    {
        'brand_slug': 'mizuno',
        'name': 'Wave Inspire 20',
        'slug': 'mizuno-wave-inspire-20',
        'description': '미즈노 안정화. 웨이브 플레이트로 내측 지지력 강화',
        'product_type': 'stability',
        'usage': 'daily',
        'price_min': 159000,
        'price_max': 179000,
        'release_year': 2024,
        'version_number': 20,
        'specs': {'weight': '290', 'stack_height': '32', 'drop': '12', 'upper': '에어메쉬', 'midsole': '미즈노 에너지 + 웨이브 플레이트'},
        'scores': {'cushion': 85, 'responsiveness': 72, 'stability': 90, 'durability': 88},
    },
]

# ============================================================================
# 치킨 제품 데이터 (Product = 메뉴, Brand = 프랜차이즈)
# ============================================================================
CHICKEN_DATA = [
    # ---- BBQ ----
    {
        'brand_slug': 'bbq',
        'name': '황금올리브 콤보',
        'slug': 'bbq-golden-olive-combo',
        'description': 'BBQ 시그니처 메뉴. 올리브유로 바삭하게 튀긴 프리미엄 치킨',
        'product_type': 'fried',
        'usage': 'party',
        'price_min': 27000,
        'price_max': 27000,
        'specs': {'price': '27000', 'calories': '1850', 'serving': '1000', 'spicy_level': '없음', 'cooking_method': '올리브유 튀김'},
        'scores': {'taste': 95, 'price': 82, 'crispy': 96, 'popularity': 98},
    },
    {
        'brand_slug': 'bbq',
        'name': '자메이카 통다리 구이',
        'slug': 'bbq-jamaica-drumstick',
        'description': '스모키한 자메이카 스파이스로 구운 통다리 치킨',
        'product_type': 'roasted',
        'usage': 'beer',
        'price_min': 24000,
        'price_max': 24000,
        'specs': {'price': '24000', 'calories': '1450', 'serving': '850', 'spicy_level': '중간', 'cooking_method': '오븐 구이'},
        'scores': {'taste': 92, 'price': 78, 'crispy': 75, 'popularity': 88},
    },
    {
        'brand_slug': 'bbq',
        'name': '황금올리브 블랙페퍼',
        'slug': 'bbq-golden-olive-black-pepper',
        'description': '황금올리브에 블랙페퍼 시즈닝을 더한 스파이시 버전',
        'product_type': 'fried',
        'usage': 'beer',
        'price_min': 21000,
        'price_max': 21000,
        'specs': {'price': '21000', 'calories': '1750', 'serving': '950', 'spicy_level': '약간', 'cooking_method': '올리브유 튀김'},
        'scores': {'taste': 90, 'price': 85, 'crispy': 94, 'popularity': 85},
    },
    # ---- 교촌 ----
    {
        'brand_slug': 'kyochon',
        'name': '허니콤보',
        'slug': 'kyochon-honey-combo',
        'description': '꿀과 간장의 조화. 달콤짭짤한 교촌의 베스트셀러',
        'product_type': 'soy',
        'usage': 'family',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1650', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+소스'},
        'scores': {'taste': 94, 'price': 82, 'crispy': 88, 'popularity': 96},
    },
    {
        'brand_slug': 'kyochon',
        'name': '레드콤보',
        'slug': 'kyochon-red-combo',
        'description': '매콤한 교촌만의 레드 시즈닝. 매운맛 마니아 필수',
        'product_type': 'seasoned',
        'usage': 'beer',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1700', 'serving': '900', 'spicy_level': '매움', 'cooking_method': '튀김+양념'},
        'scores': {'taste': 92, 'price': 82, 'crispy': 86, 'popularity': 92},
    },
    {
        'brand_slug': 'kyochon',
        'name': '교촌오리지날',
        'slug': 'kyochon-original-soy',
        'description': '교촌의 시작. 간장 베이스의 원조 간장치킨',
        'product_type': 'soy',
        'usage': 'family',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1600', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+간장소스'},
        'scores': {'taste': 95, 'price': 80, 'crispy': 85, 'popularity': 95},
    },
    # ---- BHC ----
    {
        'brand_slug': 'bhc',
        'name': '뿌링클',
        'slug': 'bhc-puringkle-original',
        'description': 'MZ세대 인기 1위. 치즈 시즈닝과 뿌링뿌링 소스의 환상조합',
        'product_type': 'cheese',
        'usage': 'party',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '2320', 'serving': '1100', 'spicy_level': '없음', 'cooking_method': '튀김+치즈 시즈닝'},
        'scores': {'taste': 94, 'price': 85, 'crispy': 92, 'popularity': 98},
    },
    {
        'brand_slug': 'bhc',
        'name': '뿌링클 핫',
        'slug': 'bhc-puringkle-hot',
        'description': '뿌링클에 매직 핫 시즈닝을 더한 매콤 버전',
        'product_type': 'cheese',
        'usage': 'beer',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '2350', 'serving': '1100', 'spicy_level': '매움', 'cooking_method': '튀김+핫 시즈닝'},
        'scores': {'taste': 92, 'price': 85, 'crispy': 90, 'popularity': 90},
    },
    {
        'brand_slug': 'bhc',
        'name': '맛초킹',
        'slug': 'bhc-matchoking-original',
        'description': '고추장 베이스의 매콤달콤. 쫄깃한 튀김옷이 특징',
        'product_type': 'seasoned',
        'usage': 'beer',
        'price_min': 21000,
        'price_max': 23000,
        'specs': {'price': '21000', 'calories': '1850', 'serving': '950', 'spicy_level': '매움', 'cooking_method': '튀김+양념'},
        'scores': {'taste': 88, 'price': 82, 'crispy': 82, 'popularity': 85},
    },
    # ---- 굽네 ----
    {
        'brand_slug': 'goobne',
        'name': '고추바사삭',
        'slug': 'goobne-gochu-basasak',
        'description': '오븐에 구워 담백하고 바삭한 굽네 시그니처',
        'product_type': 'roasted',
        'usage': 'family',
        'price_min': 19900,
        'price_max': 22900,
        'specs': {'price': '19900', 'calories': '1350', 'serving': '800', 'spicy_level': '중간', 'cooking_method': '오븐 구이'},
        'scores': {'taste': 90, 'price': 85, 'crispy': 88, 'popularity': 88},
    },
    {
        'brand_slug': 'goobne',
        'name': '볼케이노',
        'slug': 'goobne-volcano',
        'description': '화끈하게 매운 굽네의 불닭 메뉴',
        'product_type': 'roasted',
        'usage': 'beer',
        'price_min': 20900,
        'price_max': 22900,
        'specs': {'price': '20900', 'calories': '1450', 'serving': '850', 'spicy_level': '아주 매움', 'cooking_method': '오븐 구이+소스'},
        'scores': {'taste': 85, 'price': 82, 'crispy': 80, 'popularity': 78},
    },
    {
        'brand_slug': 'goobne',
        'name': '오리지널',
        'slug': 'goobne-original',
        'description': '굽네의 기본. 담백하고 깔끔한 오븐 구이 치킨',
        'product_type': 'roasted',
        'usage': 'family',
        'price_min': 17900,
        'price_max': 20900,
        'specs': {'price': '17900', 'calories': '1200', 'serving': '750', 'spicy_level': '없음', 'cooking_method': '오븐 구이'},
        'scores': {'taste': 85, 'price': 88, 'crispy': 82, 'popularity': 82},
    },
    # ---- 네네 ----
    {
        'brand_slug': 'nene',
        'name': '치즈스노윙',
        'slug': 'nene-cheese-snowing',
        'description': '눈꽃치즈가 흩날리는 네네의 시그니처',
        'product_type': 'cheese',
        'usage': 'party',
        'price_min': 22000,
        'price_max': 23000,
        'specs': {'price': '22000', 'calories': '2100', 'serving': '1000', 'spicy_level': '없음', 'cooking_method': '튀김+치즈 토핑'},
        'scores': {'taste': 90, 'price': 80, 'crispy': 85, 'popularity': 88},
    },
    {
        'brand_slug': 'nene',
        'name': '스노윙MAXX',
        'slug': 'nene-snowing-maxx',
        'description': '더 많은 치즈, 더 풍성한 맛. 스노윙의 업그레이드 버전',
        'product_type': 'cheese',
        'usage': 'party',
        'price_min': 23000,
        'price_max': 23000,
        'specs': {'price': '23000', 'calories': '2250', 'serving': '1050', 'spicy_level': '없음', 'cooking_method': '튀김+치즈 토핑'},
        'scores': {'taste': 92, 'price': 78, 'crispy': 85, 'popularity': 85},
    },
    {
        'brand_slug': 'nene',
        'name': '오리엔탈파닭',
        'slug': 'nene-oriental-padak',
        'description': '파채와 오리엔탈 소스의 조화. 맥주 안주로 최고',
        'product_type': 'fried',
        'usage': 'beer',
        'price_min': 23000,
        'price_max': 23000,
        'specs': {'price': '23000', 'calories': '1800', 'serving': '950', 'spicy_level': '없음', 'cooking_method': '튀김+파채 토핑'},
        'scores': {'taste': 88, 'price': 78, 'crispy': 88, 'popularity': 82},
    },
    # ---- 푸라닭 ----
    {
        'brand_slug': 'puradak',
        'name': '블랙알리오',
        'slug': 'puradak-black-allio-original',
        'description': '간장과 마늘의 깊은 풍미. 푸라닭 시그니처 메뉴',
        'product_type': 'garlic',
        'usage': 'beer',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '1750', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+마늘소스'},
        'scores': {'taste': 93, 'price': 78, 'crispy': 88, 'popularity': 85},
    },
    {
        'brand_slug': 'puradak',
        'name': '고추마요',
        'slug': 'puradak-gochu-mayo',
        'description': '청양고추와 마요네즈의 조화. 매콤크리미한 맛',
        'product_type': 'seasoned',
        'usage': 'beer',
        'price_min': 22000,
        'price_max': 24000,
        'specs': {'price': '22000', 'calories': '1950', 'serving': '900', 'spicy_level': '중간', 'cooking_method': '튀김+마요소스'},
        'scores': {'taste': 90, 'price': 78, 'crispy': 85, 'popularity': 82},
    },
    # ---- 호식이 ----
    {
        'brand_slug': 'hosigi',
        'name': '호식이 후라이드+후라이드',
        'slug': 'hosigi-double-fried',
        'description': '두마리 치킨의 원조. 옛날통닭 스타일 후라이드',
        'product_type': 'fried',
        'usage': 'family',
        'price_min': 25000,
        'price_max': 25000,
        'specs': {'price': '25000', 'calories': '2800', 'serving': '1600', 'spicy_level': '없음', 'cooking_method': '튀김'},
        'scores': {'taste': 80, 'price': 95, 'crispy': 82, 'popularity': 78},
    },
    {
        'brand_slug': 'hosigi',
        'name': '레몬크림탕슈',
        'slug': 'hosigi-lemon-cream',
        'description': '상큼한 레몬과 크리미한 소스. 호식이의 인기 신메뉴',
        'product_type': 'seasoned',
        'usage': 'party',
        'price_min': 26000,
        'price_max': 26000,
        'specs': {'price': '26000', 'calories': '2200', 'serving': '1000', 'spicy_level': '없음', 'cooking_method': '튀김+소스'},
        'scores': {'taste': 82, 'price': 88, 'crispy': 78, 'popularity': 75},
    },
    # ---- 처갓집 ----
    {
        'brand_slug': 'cheogajip',
        'name': '슈프림골드양념',
        'slug': 'cheogajip-supreme-gold',
        'description': '진하고 달콤한 처갓집 시그니처 양념. 호불호 없는 맛',
        'product_type': 'seasoned',
        'usage': 'family',
        'price_min': 23000,
        'price_max': 25000,
        'specs': {'price': '23000', 'calories': '1900', 'serving': '950', 'spicy_level': '없음', 'cooking_method': '튀김+양념'},
        'scores': {'taste': 85, 'price': 78, 'crispy': 78, 'popularity': 75},
    },
    {
        'brand_slug': 'cheogajip',
        'name': '트러플슈프림양념',
        'slug': 'cheogajip-truffle-supreme',
        'description': '트러플 오일이 더해진 프리미엄 버전',
        'product_type': 'seasoned',
        'usage': 'party',
        'price_min': 25000,
        'price_max': 27000,
        'specs': {'price': '25000', 'calories': '1950', 'serving': '950', 'spicy_level': '없음', 'cooking_method': '튀김+트러플소스'},
        'scores': {'taste': 88, 'price': 72, 'crispy': 78, 'popularity': 72},
    },
    # ---- 60계 ----
    {
        'brand_slug': '60gye',
        'name': '후라이드',
        'slug': '60gye-fried-original',
        'description': '옛날 방식 후라이드의 정석. 가성비 최고',
        'product_type': 'fried',
        'usage': 'solo',
        'price_min': 22900,
        'price_max': 24900,
        'specs': {'price': '22900', 'calories': '1650', 'serving': '850', 'spicy_level': '없음', 'cooking_method': '튀김'},
        'scores': {'taste': 75, 'price': 95, 'crispy': 80, 'popularity': 75},
    },
    {
        'brand_slug': '60gye',
        'name': '크크크치킨',
        'slug': '60gye-ccc-chicken',
        'description': '크런치 크럼블 크리스피. 콘크럼블 시즈닝이 특징',
        'product_type': 'fried',
        'usage': 'solo',
        'price_min': 23900,
        'price_max': 25900,
        'specs': {'price': '23900', 'calories': '1800', 'serving': '900', 'spicy_level': '없음', 'cooking_method': '튀김+시즈닝'},
        'scores': {'taste': 78, 'price': 92, 'crispy': 88, 'popularity': 72},
    },
]

# ============================================================================
# 남자시계 제품 데이터
# ============================================================================
MENS_WATCH_DATA = [
    # ---- 파텍 필립 ----
    {
        'brand_slug': 'patek-philippe',
        'name': '노틸러스 5711/1A',
        'slug': 'patek-nautilus-5711-1a',
        'description': '럭셔리 스포츠워치의 아이콘. 제럴드 젠타 디자인의 걸작',
        'product_type': 'sport',
        'usage': 'collection',
        'price_min': 100000000,
        'price_max': 150000000,
        'specs': {'case_diameter': '40', 'case_thickness': '8.3', 'water_resistance': '120', 'movement': '칼리버 26-330 S C', 'power_reserve': '45', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 100, 'resale': 100, 'prestige': 100},
    },
    {
        'brand_slug': 'patek-philippe',
        'name': '칼라트라바 5227G',
        'slug': 'patek-calatrava-5227g',
        'description': '드레스워치의 정수. 클래식한 우아함의 대명사',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 45000000,
        'price_max': 55000000,
        'specs': {'case_diameter': '39', 'case_thickness': '9.2', 'water_resistance': '30', 'movement': '칼리버 324 S C', 'power_reserve': '45', 'case_material': '18K 화이트골드', 'crystal': '사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 100, 'resale': 95, 'prestige': 98},
    },
    {
        'brand_slug': 'patek-philippe',
        'name': '아쿠아넛 5167A',
        'slug': 'patek-aquanaut-5167a',
        'description': '노틸러스의 캐주얼 버전. 스포티한 럭셔리',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 70000000,
        'price_max': 90000000,
        'specs': {'case_diameter': '40', 'case_thickness': '8.1', 'water_resistance': '120', 'movement': '칼리버 324 S C', 'power_reserve': '45', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 98, 'resale': 98, 'prestige': 98},
    },
    # ---- 롤렉스 ----
    {
        'brand_slug': 'rolex',
        'name': '서브마리너 126610LN',
        'slug': 'rolex-submariner-126610ln',
        'description': '다이버워치의 기준. 결국 돌고 돌아 롤렉스',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 16500000,
        'price_max': 22000000,
        'specs': {'case_diameter': '41', 'case_thickness': '12.5', 'water_resistance': '300', 'movement': '칼리버 3235', 'power_reserve': '70', 'case_material': '오이스터스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 98, 'craftsmanship': 95, 'resale': 100, 'prestige': 98},
    },
    {
        'brand_slug': 'rolex',
        'name': '데이토나 126500LN',
        'slug': 'rolex-daytona-126500ln',
        'description': '레이싱 크로노그래프의 전설. 세라토나',
        'product_type': 'chronograph',
        'usage': 'collection',
        'price_min': 35000000,
        'price_max': 55000000,
        'specs': {'case_diameter': '40', 'case_thickness': '12.2', 'water_resistance': '100', 'movement': '칼리버 4131', 'power_reserve': '72', 'case_material': '오이스터스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 95, 'resale': 100, 'prestige': 100},
    },
    {
        'brand_slug': 'rolex',
        'name': 'GMT-마스터 II 126710BLNR',
        'slug': 'rolex-gmt-master-126710blnr',
        'description': 'GMT 기능의 완성. 배트맨이라 불리는 인기 모델',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 13500000,
        'price_max': 25000000,
        'specs': {'case_diameter': '40', 'case_thickness': '12', 'water_resistance': '100', 'movement': '칼리버 3285', 'power_reserve': '70', 'case_material': '오이스터스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 98, 'craftsmanship': 95, 'resale': 98, 'prestige': 98},
    },
    {
        'brand_slug': 'rolex',
        'name': '데이저스트 126334',
        'slug': 'rolex-datejust-126334',
        'description': '롤렉스 클래식의 정수. 41mm 모던 버전',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 12000000,
        'price_max': 16000000,
        'specs': {'case_diameter': '41', 'case_thickness': '11.8', 'water_resistance': '100', 'movement': '칼리버 3235', 'power_reserve': '70', 'case_material': '오이스터스틸+화이트골드', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 92, 'resale': 92, 'prestige': 95},
    },
    # ---- 오데마 피게 ----
    {
        'brand_slug': 'audemars-piguet',
        'name': '로열오크 15500ST',
        'slug': 'ap-royal-oak-15500st',
        'description': '럭셔리 스포츠워치의 창시자. 제럴드 젠타의 걸작',
        'product_type': 'sport',
        'usage': 'collection',
        'price_min': 45000000,
        'price_max': 60000000,
        'specs': {'case_diameter': '41', 'case_thickness': '10.4', 'water_resistance': '50', 'movement': '칼리버 4302', 'power_reserve': '70', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 98, 'craftsmanship': 100, 'resale': 98, 'prestige': 100},
    },
    {
        'brand_slug': 'audemars-piguet',
        'name': '로열오크 오프쇼어 26470ST',
        'slug': 'ap-royal-oak-offshore-26470st',
        'description': '더 크고 강한 로열오크. 스포츠 크로노그래프',
        'product_type': 'chronograph',
        'usage': 'sport',
        'price_min': 55000000,
        'price_max': 70000000,
        'specs': {'case_diameter': '42', 'case_thickness': '14.2', 'water_resistance': '100', 'movement': '칼리버 3126/3840', 'power_reserve': '50', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 98, 'resale': 95, 'prestige': 98},
    },
    # ---- 오메가 ----
    {
        'brand_slug': 'omega',
        'name': '스피드마스터 문워치 프로',
        'slug': 'omega-speedmaster-moonwatch-pro',
        'description': '달에 간 시계. NASA 공인 우주 시계',
        'product_type': 'chronograph',
        'usage': 'casual',
        'price_min': 9500000,
        'price_max': 11000000,
        'specs': {'case_diameter': '42', 'case_thickness': '13.2', 'water_resistance': '50', 'movement': '칼리버 3861', 'power_reserve': '50', 'case_material': '스테인리스 스틸', 'crystal': '헤잘라이트/사파이어'},
        'scores': {'heritage': 100, 'craftsmanship': 92, 'resale': 85, 'prestige': 95},
    },
    {
        'brand_slug': 'omega',
        'name': '씨마스터 300M 다이버',
        'slug': 'omega-seamaster-300m',
        'description': '제임스 본드의 시계. 세라믹 베젤의 프로 다이버',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 7500000,
        'price_max': 9000000,
        'specs': {'case_diameter': '42', 'case_thickness': '13.6', 'water_resistance': '300', 'movement': '칼리버 8800', 'power_reserve': '55', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 92, 'resale': 82, 'prestige': 90},
    },
    {
        'brand_slug': 'omega',
        'name': '아쿠아 테라 150M',
        'slug': 'omega-aqua-terra-150m',
        'description': '비즈니스와 스포츠의 완벽한 조화',
        'product_type': 'sport',
        'usage': 'formal',
        'price_min': 8500000,
        'price_max': 10500000,
        'specs': {'case_diameter': '41', 'case_thickness': '13.2', 'water_resistance': '150', 'movement': '칼리버 8900', 'power_reserve': '60', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 92, 'craftsmanship': 92, 'resale': 80, 'prestige': 88},
    },
    # ---- 태그호이어 ----
    {
        'brand_slug': 'tag-heuer',
        'name': '카레라 크로노그래프',
        'slug': 'tag-heuer-carrera-chrono',
        'description': '모터스포츠 헤리티지. 클래식 레이싱 크로노그래프',
        'product_type': 'chronograph',
        'usage': 'casual',
        'price_min': 6000000,
        'price_max': 8000000,
        'specs': {'case_diameter': '44', 'case_thickness': '14.5', 'water_resistance': '100', 'movement': '칼리버 TH20-00', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 90, 'craftsmanship': 82, 'resale': 70, 'prestige': 82},
    },
    {
        'brand_slug': 'tag-heuer',
        'name': '모나코',
        'slug': 'tag-heuer-monaco',
        'description': '스티브 맥퀸의 시계. 세계 최초 사각 자동 크로노',
        'product_type': 'chronograph',
        'usage': 'casual',
        'price_min': 8000000,
        'price_max': 10000000,
        'specs': {'case_diameter': '39', 'case_thickness': '14', 'water_resistance': '100', 'movement': '칼리버 11', 'power_reserve': '40', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 82, 'resale': 75, 'prestige': 88},
    },
    {
        'brand_slug': 'tag-heuer',
        'name': '아쿠아레이서 300',
        'slug': 'tag-heuer-aquaracer-300',
        'description': '다이버 워치의 새로운 기준. 세라믹 베젤 적용',
        'product_type': 'diver',
        'usage': 'sport',
        'price_min': 4500000,
        'price_max': 6000000,
        'specs': {'case_diameter': '42', 'case_thickness': '12', 'water_resistance': '300', 'movement': '칼리버 TH30', 'power_reserve': '60', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 80, 'resale': 68, 'prestige': 78},
    },
    # ---- IWC ----
    {
        'brand_slug': 'iwc',
        'name': '빅 파일럿 43',
        'slug': 'iwc-big-pilot-43',
        'description': '파일럿 워치의 대명사. 역사적 항법 기구의 현대적 해석',
        'product_type': 'pilot',
        'usage': 'casual',
        'price_min': 12000000,
        'price_max': 15000000,
        'specs': {'case_diameter': '43', 'case_thickness': '13.6', 'water_resistance': '100', 'movement': '칼리버 82100', 'power_reserve': '60', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 95, 'craftsmanship': 92, 'resale': 82, 'prestige': 90},
    },
    {
        'brand_slug': 'iwc',
        'name': '포르투기스 크로노',
        'slug': 'iwc-portugieser-chrono',
        'description': '항해 시계의 우아함. IWC의 스테디셀러',
        'product_type': 'chronograph',
        'usage': 'formal',
        'price_min': 9700000,
        'price_max': 12000000,
        'specs': {'case_diameter': '41', 'case_thickness': '13.5', 'water_resistance': '30', 'movement': '칼리버 69355', 'power_reserve': '46', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 92, 'craftsmanship': 92, 'resale': 80, 'prestige': 88},
    },
    # ---- 그랜드 세이코 ----
    {
        'brand_slug': 'grand-seiko',
        'name': 'SBGA211 스노우플레이크',
        'slug': 'grand-seiko-sbga211',
        'description': '설경 다이얼의 아름다움. 스프링 드라이브의 정수',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 8400000,
        'price_max': 9500000,
        'specs': {'case_diameter': '41', 'case_thickness': '12.3', 'water_resistance': '100', 'movement': '스프링 드라이브 9R65', 'power_reserve': '72', 'case_material': '하이인텐시티 티타늄', 'crystal': '사파이어'},
        'scores': {'heritage': 88, 'craftsmanship': 98, 'resale': 75, 'prestige': 88},
    },
    {
        'brand_slug': 'grand-seiko',
        'name': 'SBGW285 엘레강스',
        'slug': 'grand-seiko-sbgw285',
        'description': '수동 와인딩의 정수. 심플한 우아함',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 5200000,
        'price_max': 6000000,
        'specs': {'case_diameter': '37.3', 'case_thickness': '10.3', 'water_resistance': '30', 'movement': '9S64', 'power_reserve': '72', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 95, 'resale': 70, 'prestige': 82},
    },
    # ---- 튜더 ----
    {
        'brand_slug': 'tudor',
        'name': '블랙 베이 58',
        'slug': 'tudor-black-bay-58',
        'description': '롤렉스의 동생. 가성비 최고의 럭셔리 다이버',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 5200000,
        'price_max': 6000000,
        'specs': {'case_diameter': '39', 'case_thickness': '11.9', 'water_resistance': '200', 'movement': 'MT5402', 'power_reserve': '70', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 85, 'resale': 78, 'prestige': 82},
    },
    {
        'brand_slug': 'tudor',
        'name': '펠라고스 FXD',
        'slug': 'tudor-pelagos-fxd',
        'description': '밀리터리 스펙 다이버. 티타늄 케이스의 프로 도구',
        'product_type': 'diver',
        'usage': 'sport',
        'price_min': 6000000,
        'price_max': 7000000,
        'specs': {'case_diameter': '42', 'case_thickness': '12.3', 'water_resistance': '200', 'movement': 'MT5602', 'power_reserve': '70', 'case_material': '티타늄', 'crystal': '사파이어'},
        'scores': {'heritage': 82, 'craftsmanship': 88, 'resale': 75, 'prestige': 80},
    },
    # ---- 티쏘 ----
    {
        'brand_slug': 'tissot',
        'name': 'PRX 파워매틱 80',
        'slug': 'tissot-prx-powermatic-80',
        'description': '70년대 레트로 디자인의 부활. 가성비 럭셔리 스포츠워치',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 850000,
        'price_max': 960000,
        'specs': {'case_diameter': '40', 'case_thickness': '10.9', 'water_resistance': '100', 'movement': '파워매틱 80.111', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 78, 'craftsmanship': 75, 'resale': 55, 'prestige': 68},
    },
    {
        'brand_slug': 'tissot',
        'name': '젠틀맨 파워매틱 80',
        'slug': 'tissot-gentleman-powermatic-80',
        'description': '비즈니스 캐주얼의 정석. 깔끔한 드레스워치',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 900000,
        'price_max': 1100000,
        'specs': {'case_diameter': '40', 'case_thickness': '11', 'water_resistance': '100', 'movement': '파워매틱 80.111', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 78, 'craftsmanship': 75, 'resale': 50, 'prestige': 65},
    },
    # ---- 해밀턴 ----
    {
        'brand_slug': 'hamilton',
        'name': '카키 필드 오토매틱 38',
        'slug': 'hamilton-khaki-field-38',
        'description': '밀리터리 필드워치의 전설. 영화 속 단골 시계',
        'product_type': 'pilot',
        'usage': 'casual',
        'price_min': 750000,
        'price_max': 900000,
        'specs': {'case_diameter': '38', 'case_thickness': '9.5', 'water_resistance': '100', 'movement': 'H-10', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 85, 'craftsmanship': 72, 'resale': 50, 'prestige': 65},
    },
    {
        'brand_slug': 'hamilton',
        'name': '벤츄라 오토매틱',
        'slug': 'hamilton-ventura-auto',
        'description': '엘비스 프레슬리의 시계. 세계 최초 전기 시계의 디자인',
        'product_type': 'dress',
        'usage': 'casual',
        'price_min': 1200000,
        'price_max': 1500000,
        'specs': {'case_diameter': '42.5', 'case_thickness': '12.1', 'water_resistance': '50', 'movement': 'H-10', 'power_reserve': '80', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 90, 'craftsmanship': 70, 'resale': 48, 'prestige': 68},
    },
    # ---- 세이코 ----
    {
        'brand_slug': 'seiko',
        'name': 'SKX007',
        'slug': 'seiko-skx007',
        'description': '전설의 가성비 다이버. 모딩의 바이블 (단종)',
        'product_type': 'diver',
        'usage': 'casual',
        'price_min': 400000,
        'price_max': 600000,
        'specs': {'case_diameter': '42', 'case_thickness': '13.4', 'water_resistance': '200', 'movement': '7S26', 'power_reserve': '41', 'case_material': '스테인리스 스틸', 'crystal': '하드렉스'},
        'scores': {'heritage': 88, 'craftsmanship': 72, 'resale': 55, 'prestige': 65},
    },
    {
        'brand_slug': 'seiko',
        'name': '프레사지 샤프엣지',
        'slug': 'seiko-presage-sharp-edged',
        'description': '일본 전통미와 현대적 디자인의 조화',
        'product_type': 'dress',
        'usage': 'formal',
        'price_min': 600000,
        'price_max': 800000,
        'specs': {'case_diameter': '39.3', 'case_thickness': '11.1', 'water_resistance': '100', 'movement': '6R35', 'power_reserve': '70', 'case_material': '스테인리스 스틸', 'crystal': '사파이어'},
        'scores': {'heritage': 82, 'craftsmanship': 78, 'resale': 45, 'prestige': 62},
    },
    # ---- 카시오 / 지샥 ----
    {
        'brand_slug': 'casio-gshock',
        'name': 'G-SHOCK GA-2100',
        'slug': 'gshock-ga-2100',
        'description': '카시오크라 불리는 인기 모델. 슬림한 지샥',
        'product_type': 'sport',
        'usage': 'sport',
        'price_min': 120000,
        'price_max': 180000,
        'specs': {'case_diameter': '45.4', 'case_thickness': '11.8', 'water_resistance': '200', 'movement': '쿼츠 5611', 'power_reserve': '배터리 3년', 'case_material': '카본코어 수지', 'crystal': '미네랄'},
        'scores': {'heritage': 75, 'craftsmanship': 80, 'resale': 35, 'prestige': 55},
    },
    {
        'brand_slug': 'casio-gshock',
        'name': 'G-SHOCK GMW-B5000',
        'slug': 'gshock-gmw-b5000',
        'description': '오리지널 스퀘어 지샥의 풀메탈 버전',
        'product_type': 'sport',
        'usage': 'casual',
        'price_min': 550000,
        'price_max': 700000,
        'specs': {'case_diameter': '43.2', 'case_thickness': '13', 'water_resistance': '200', 'movement': '터프솔라', 'power_reserve': '솔라', 'case_material': '스테인리스 스틸', 'crystal': '미네랄'},
        'scores': {'heritage': 80, 'craftsmanship': 82, 'resale': 40, 'prestige': 58},
    },
]


# ============================================================================
# 뜨는 패션 브랜드 제품(시그니처 아이템) 데이터
# ============================================================================
FASHION_BRANDS_DATA = [
    # ---- 황제(S) 브랜드 대표 아이템 ----
    # 에르메스
    {'brand_slug': 'hermes', 'name': '버킨 30', 'slug': 'hermes-birkin-30', 'description': '전 세계에서 가장 구하기 힘든 가방. 대기 리스트 자체가 브랜드 파워의 상징', 'product_type': 'bag', 'usage': 'formal', 'price_min': 12000000, 'price_max': 20000000, 'release_year': 1984, 'specs': {'price_range': '1,200만~2,000만', 'country': '프랑스', 'founded_year': '1837', 'key_item': '버킨백'}, 'scores': {'design': 95, 'quality': 100, 'trend': 90, 'value': 98}},
    {'brand_slug': 'hermes', 'name': '켈리 28', 'slug': 'hermes-kelly-28', 'description': '그레이스 켈리가 사랑한 가방. 클래식의 정수', 'product_type': 'bag', 'usage': 'formal', 'price_min': 11000000, 'price_max': 18000000, 'release_year': 1956, 'specs': {'price_range': '1,100만~1,800만', 'country': '프랑스', 'founded_year': '1837', 'key_item': '켈리백'}, 'scores': {'design': 93, 'quality': 100, 'trend': 85, 'value': 97}},
    # 샤넬
    {'brand_slug': 'chanel', 'name': '클래식 플랩백 미듐', 'slug': 'chanel-classic-flap', 'description': '샤넬의 상징. 매년 가격 인상에도 웨이팅이 끊이지 않는 아이코닉 백', 'product_type': 'bag', 'usage': 'formal', 'price_min': 13000000, 'price_max': 15000000, 'release_year': 1983, 'specs': {'price_range': '1,300만~1,500만', 'country': '프랑스', 'founded_year': '1910', 'key_item': '클래식 플랩백'}, 'scores': {'design': 90, 'quality': 95, 'trend': 85, 'value': 95}},
    {'brand_slug': 'chanel', 'name': '트위드 재킷', 'slug': 'chanel-tweed-jacket', 'description': '코코 샤넬이 만든 여성 패션의 혁명. 시즌마다 새로운 트위드로 재해석', 'product_type': 'outerwear', 'usage': 'formal', 'price_min': 8000000, 'price_max': 15000000, 'release_year': 1954, 'specs': {'price_range': '800만~1,500만', 'country': '프랑스', 'founded_year': '1910', 'key_item': '트위드 재킷'}, 'scores': {'design': 92, 'quality': 95, 'trend': 82, 'value': 90}},
    # 미우미우
    {'brand_slug': 'miu-miu', 'name': '완더 백', 'slug': 'miumiu-wander-bag', 'description': 'Lyst Index 1위 브랜드의 시그니처. 부드러운 나파 레더와 마틀라세 패턴', 'product_type': 'bag', 'usage': 'casual', 'price_min': 2500000, 'price_max': 3500000, 'release_year': 2022, 'specs': {'price_range': '250만~350만', 'country': '이탈리아', 'founded_year': '1993', 'key_item': '완더 백'}, 'scores': {'design': 95, 'quality': 85, 'trend': 98, 'value': 80}},
    {'brand_slug': 'miu-miu', 'name': '로우라이즈 플리츠 스커트', 'slug': 'miumiu-pleated-skirt', 'description': 'Y2K 트렌드를 이끈 아이코닉 스커트. MZ세대 워너비 아이템', 'product_type': 'accessory', 'usage': 'casual', 'price_min': 1500000, 'price_max': 2200000, 'release_year': 2022, 'specs': {'price_range': '150만~220만', 'country': '이탈리아', 'founded_year': '1993', 'key_item': '미니스커트'}, 'scores': {'design': 96, 'quality': 82, 'trend': 99, 'value': 75}},
    # 로에베
    {'brand_slug': 'loewe', 'name': '퍼즐 백', 'slug': 'loewe-puzzle-bag', 'description': '조나단 앤더슨의 기하학적 디자인. 크래프트 럭셔리의 정수', 'product_type': 'bag', 'usage': 'casual', 'price_min': 3500000, 'price_max': 5000000, 'release_year': 2015, 'specs': {'price_range': '350만~500만', 'country': '스페인', 'founded_year': '1846', 'key_item': '퍼즐백'}, 'scores': {'design': 97, 'quality': 92, 'trend': 95, 'value': 85}},
    {'brand_slug': 'loewe', 'name': '바스켓 백', 'slug': 'loewe-basket-bag', 'description': '야자잎과 가죽의 조합. 여름 시즌 대표 잇백', 'product_type': 'bag', 'usage': 'casual', 'price_min': 600000, 'price_max': 900000, 'release_year': 2018, 'specs': {'price_range': '60만~90만', 'country': '스페인', 'founded_year': '1846', 'key_item': '바스켓백'}, 'scores': {'design': 90, 'quality': 88, 'trend': 92, 'value': 82}},
    # 더 로우
    {'brand_slug': 'the-row', 'name': '마고 백', 'slug': 'the-row-margaux-bag', 'description': '콰이어트 럭셔리의 교과서. 로고 없이 소재와 실루엣으로 승부', 'product_type': 'bag', 'usage': 'formal', 'price_min': 4000000, 'price_max': 6000000, 'release_year': 2018, 'specs': {'price_range': '400만~600만', 'country': '미국', 'founded_year': '2006', 'key_item': '마고백'}, 'scores': {'design': 92, 'quality': 95, 'trend': 90, 'value': 88}},
    {'brand_slug': 'the-row', 'name': '캐시미어 크루넥 니트', 'slug': 'the-row-cashmere-knit', 'description': '12게이지 캐시미어. 입어본 사람만 아는 질감의 차이', 'product_type': 'knitwear', 'usage': 'casual', 'price_min': 1500000, 'price_max': 3000000, 'release_year': 2020, 'specs': {'price_range': '150만~300만', 'country': '미국', 'founded_year': '2006', 'key_item': '캐시미어 니트'}, 'scores': {'design': 88, 'quality': 98, 'trend': 85, 'value': 85}},
    # 브루넬로 쿠치넬리
    {'brand_slug': 'brunello-cucinelli', 'name': '캐시미어 집업 니트', 'slug': 'cucinelli-cashmere-zip', 'description': '실리콘밸리 CEO 유니폼. 캐시미어의 왕이 만든 궁극의 니트', 'product_type': 'knitwear', 'usage': 'casual', 'price_min': 3000000, 'price_max': 5000000, 'release_year': 2022, 'specs': {'price_range': '300만~500만', 'country': '이탈리아', 'founded_year': '1978', 'key_item': '캐시미어 니트'}, 'scores': {'design': 85, 'quality': 98, 'trend': 82, 'value': 92}},
    {'brand_slug': 'brunello-cucinelli', 'name': '스웨이드 봄버 재킷', 'slug': 'cucinelli-suede-bomber', 'description': '이탈리안 장인이 만든 스웨이드 재킷. 콰이어트 럭셔리의 정석', 'product_type': 'outerwear', 'usage': 'casual', 'price_min': 6000000, 'price_max': 10000000, 'release_year': 2023, 'specs': {'price_range': '600만~1,000만', 'country': '이탈리아', 'founded_year': '1978', 'key_item': '스웨이드 재킷'}, 'scores': {'design': 88, 'quality': 97, 'trend': 80, 'value': 90}},

    # ---- 왕(A) 브랜드 대표 아이템 ----
    # 보테가 베네타
    {'brand_slug': 'bottega-veneta', 'name': '카세트 백', 'slug': 'bottega-cassette-bag', 'description': '인트레치아토 위빙의 모던 해석. 다니엘 리가 만든 뉴 클래식', 'product_type': 'bag', 'usage': 'casual', 'price_min': 3500000, 'price_max': 5000000, 'release_year': 2019, 'specs': {'price_range': '350만~500만', 'country': '이탈리아', 'founded_year': '1966', 'key_item': '카세트백'}, 'scores': {'design': 90, 'quality': 92, 'trend': 82, 'value': 78}},
    {'brand_slug': 'bottega-veneta', 'name': '조디 백', 'slug': 'bottega-jodie-bag', 'description': '매듭 디테일의 호보백. 인트레치아토 + 미니멀의 완벽한 균형', 'product_type': 'bag', 'usage': 'casual', 'price_min': 4000000, 'price_max': 5500000, 'release_year': 2020, 'specs': {'price_range': '400만~550만', 'country': '이탈리아', 'founded_year': '1966', 'key_item': '조디백'}, 'scores': {'design': 88, 'quality': 90, 'trend': 80, 'value': 75}},
    # 프라다
    {'brand_slug': 'prada', 'name': '리나일론 숄더백', 'slug': 'prada-re-nylon-bag', 'description': '재생 나일론으로 만든 지속가능한 럭셔리. 힙한 명품의 상징', 'product_type': 'bag', 'usage': 'casual', 'price_min': 1800000, 'price_max': 2800000, 'release_year': 2019, 'specs': {'price_range': '180만~280만', 'country': '이탈리아', 'founded_year': '1913', 'key_item': '리나일론백'}, 'scores': {'design': 85, 'quality': 85, 'trend': 88, 'value': 80}},
    {'brand_slug': 'prada', 'name': '리나일론 봄버 재킷', 'slug': 'prada-re-nylon-jacket', 'description': '라프 시몬스 합류 후의 뉴 프라다. 스포티하면서 럭셔리한 균형', 'product_type': 'outerwear', 'usage': 'street', 'price_min': 2500000, 'price_max': 4000000, 'release_year': 2021, 'specs': {'price_range': '250만~400만', 'country': '이탈리아', 'founded_year': '1913', 'key_item': '리나일론 재킷'}, 'scores': {'design': 82, 'quality': 88, 'trend': 85, 'value': 78}},
    # 아크테릭스
    {'brand_slug': 'arcteryx', 'name': '알파 SV 재킷', 'slug': 'arcteryx-alpha-sv', 'description': '고프코어 트렌드의 정점. 고어텍스 프로 최상위 아우터', 'product_type': 'outerwear', 'usage': 'outdoor', 'price_min': 900000, 'price_max': 1100000, 'release_year': 2023, 'specs': {'price_range': '90만~110만', 'country': '캐나다', 'founded_year': '1989', 'key_item': '알파 SV'}, 'scores': {'design': 82, 'quality': 98, 'trend': 92, 'value': 70}},
    {'brand_slug': 'arcteryx', 'name': '베타 LT 재킷', 'slug': 'arcteryx-beta-lt', 'description': '도심+아웃도어 겸용 쉘. 패피들의 사계절 아우터', 'product_type': 'outerwear', 'usage': 'outdoor', 'price_min': 600000, 'price_max': 750000, 'release_year': 2023, 'specs': {'price_range': '60만~75만', 'country': '캐나다', 'founded_year': '1989', 'key_item': '베타 LT'}, 'scores': {'design': 78, 'quality': 95, 'trend': 88, 'value': 72}},
    # 디올
    {'brand_slug': 'dior-fashion', 'name': '새들 백', 'slug': 'dior-saddle-bag', 'description': '존 갈리아노 시절의 아이코닉 디자인을 킴 존스가 부활', 'product_type': 'bag', 'usage': 'casual', 'price_min': 4000000, 'price_max': 5500000, 'release_year': 2018, 'specs': {'price_range': '400만~550만', 'country': '프랑스', 'founded_year': '1946', 'key_item': '새들백'}, 'scores': {'design': 85, 'quality': 88, 'trend': 78, 'value': 82}},
    # 생 로랑
    {'brand_slug': 'saint-laurent', 'name': '르 5 아 7 백', 'slug': 'ysl-le-5-a-7', 'description': '미니멀한 호보백. 파리지엔 시크의 완성', 'product_type': 'bag', 'usage': 'casual', 'price_min': 2500000, 'price_max': 3500000, 'release_year': 2021, 'specs': {'price_range': '250만~350만', 'country': '프랑스', 'founded_year': '1961', 'key_item': '르 5 아 7'}, 'scores': {'design': 82, 'quality': 85, 'trend': 78, 'value': 80}},
    {'brand_slug': 'saint-laurent', 'name': '테디 재킷', 'slug': 'ysl-teddy-jacket', 'description': '록시크 무드의 바시티 재킷. 생 로랑의 쿨한 감성 집약', 'product_type': 'outerwear', 'usage': 'street', 'price_min': 3000000, 'price_max': 4000000, 'release_year': 2016, 'specs': {'price_range': '300만~400만', 'country': '프랑스', 'founded_year': '1961', 'key_item': '테디 재킷'}, 'scores': {'design': 80, 'quality': 82, 'trend': 75, 'value': 78}},
    # 셀린느
    {'brand_slug': 'celine', 'name': '트리옹프 캔버스 백', 'slug': 'celine-triomphe-bag', 'description': '셀린느의 뉴 클래식. 트리옹프 패턴의 미니멀한 캔버스 백', 'product_type': 'bag', 'usage': 'casual', 'price_min': 2800000, 'price_max': 4000000, 'release_year': 2020, 'specs': {'price_range': '280만~400만', 'country': '프랑스', 'founded_year': '1945', 'key_item': '트리옹프백'}, 'scores': {'design': 84, 'quality': 88, 'trend': 78, 'value': 80}},

    # ---- 양반(B) 브랜드 대표 아이템 ----
    {'brand_slug': 'aime-leon-dore', 'name': '뉴발란스 550 콜라보', 'slug': 'ald-nb550-collab', 'description': '프렙+스트릿의 정석. 리셀가 2배 이상', 'product_type': 'shoes', 'usage': 'street', 'price_min': 180000, 'price_max': 400000, 'release_year': 2020, 'specs': {'price_range': '18만~40만(리셀)', 'country': '미국', 'founded_year': '2014', 'key_item': 'NB 550 콜라보'}, 'scores': {'design': 88, 'quality': 75, 'trend': 85, 'value': 50}},
    {'brand_slug': 'stone-island', 'name': '와펜 패치 오버셔츠', 'slug': 'stone-island-overshirt', 'description': '나침반 와펜이 말해주는 테크니컬 캐주얼의 정체성', 'product_type': 'outerwear', 'usage': 'casual', 'price_min': 500000, 'price_max': 800000, 'release_year': 2023, 'specs': {'price_range': '50만~80만', 'country': '이탈리아', 'founded_year': '1982', 'key_item': '와펜 오버셔츠'}, 'scores': {'design': 78, 'quality': 82, 'trend': 72, 'value': 65}},
    {'brand_slug': 'maison-margiela', 'name': '타비 부츠', 'slug': 'margiela-tabi-boots', 'description': '발가락이 갈라진 아이코닉 부츠. 패션피플 시그널', 'product_type': 'shoes', 'usage': 'casual', 'price_min': 1200000, 'price_max': 1800000, 'release_year': 1988, 'specs': {'price_range': '120만~180만', 'country': '프랑스', 'founded_year': '1988', 'key_item': '타비 부츠'}, 'scores': {'design': 95, 'quality': 82, 'trend': 72, 'value': 60}},
    {'brand_slug': 'maison-margiela', 'name': '레플리카 스니커즈', 'slug': 'margiela-replica-sneakers', 'description': '독일군 훈련화에서 영감받은 미니멀 스니커즈', 'product_type': 'shoes', 'usage': 'casual', 'price_min': 600000, 'price_max': 800000, 'release_year': 2002, 'specs': {'price_range': '60만~80만', 'country': '프랑스', 'founded_year': '1988', 'key_item': '레플리카 스니커즈'}, 'scores': {'design': 82, 'quality': 78, 'trend': 68, 'value': 58}},
    {'brand_slug': 'acne-studios', 'name': '페이스 패치 머플러', 'slug': 'acne-face-scarf', 'description': '스칸디 미니멀의 아이콘. 겨울 필수 아이템', 'product_type': 'accessory', 'usage': 'casual', 'price_min': 250000, 'price_max': 350000, 'release_year': 2018, 'specs': {'price_range': '25만~35만', 'country': '스웨덴', 'founded_year': '1996', 'key_item': '페이스 머플러'}, 'scores': {'design': 80, 'quality': 78, 'trend': 75, 'value': 55}},
    {'brand_slug': 'our-legacy', 'name': '컴프 셔츠', 'slug': 'our-legacy-comp-shirt', 'description': 'Reddit MFA 추천 1위. 독특한 실루엣의 오버사이즈 셔츠', 'product_type': 'outerwear', 'usage': 'casual', 'price_min': 250000, 'price_max': 400000, 'release_year': 2022, 'specs': {'price_range': '25만~40만', 'country': '스웨덴', 'founded_year': '2005', 'key_item': '컴프 셔츠'}, 'scores': {'design': 82, 'quality': 75, 'trend': 72, 'value': 52}},
    {'brand_slug': 'sporty-and-rich', 'name': '헬스클럽 로고 후디', 'slug': 'sporty-rich-hoodie', 'description': '올드머니 웰니스 감성의 시그니처 후디', 'product_type': 'knitwear', 'usage': 'casual', 'price_min': 200000, 'price_max': 300000, 'release_year': 2020, 'specs': {'price_range': '20만~30만', 'country': '미국', 'founded_year': '2014', 'key_item': '로고 후디'}, 'scores': {'design': 72, 'quality': 70, 'trend': 78, 'value': 45}},
    {'brand_slug': 'cos', 'name': '오버사이즈 울 코트', 'slug': 'cos-oversized-coat', 'description': '10만원대로 미니멀 럭셔리 감성. 가성비 코트의 정석', 'product_type': 'outerwear', 'usage': 'formal', 'price_min': 350000, 'price_max': 500000, 'release_year': 2023, 'specs': {'price_range': '35만~50만', 'country': '영국', 'founded_year': '2007', 'key_item': '울 코트'}, 'scores': {'design': 75, 'quality': 72, 'trend': 68, 'value': 50}},

    # ---- 중인(C) 브랜드 대표 아이템 ----
    {'brand_slug': 'bode', 'name': '퀼트 워크 재킷', 'slug': 'bode-quilted-jacket', 'description': 'CFDA 수상 디자이너의 빈티지 원단 재해석', 'product_type': 'outerwear', 'usage': 'casual', 'price_min': 800000, 'price_max': 1500000, 'release_year': 2023, 'specs': {'price_range': '80만~150만', 'country': '미국', 'founded_year': '2016', 'key_item': '퀼트 재킷'}, 'scores': {'design': 90, 'quality': 78, 'trend': 62, 'value': 38}},
    {'brand_slug': 'lemaire', 'name': '크루아상 백', 'slug': 'lemaire-croissant-bag', 'description': '유니클로 U 디자이너의 시그니처 백. 프렌치 미니멀', 'product_type': 'bag', 'usage': 'casual', 'price_min': 800000, 'price_max': 1200000, 'release_year': 2019, 'specs': {'price_range': '80만~120만', 'country': '프랑스', 'founded_year': '2000', 'key_item': '크루아상백'}, 'scores': {'design': 78, 'quality': 75, 'trend': 65, 'value': 45}},
    {'brand_slug': 'wales-bonner', 'name': '아디다스 삼바 콜라보', 'slug': 'wales-bonner-samba', 'description': '리셀가 3배 이상. 가장 핫한 스니커즈 콜라보', 'product_type': 'shoes', 'usage': 'street', 'price_min': 160000, 'price_max': 500000, 'release_year': 2023, 'specs': {'price_range': '16만~50만(리셀)', 'country': '영국', 'founded_year': '2014', 'key_item': '삼바 콜라보'}, 'scores': {'design': 80, 'quality': 72, 'trend': 72, 'value': 35}},
    {'brand_slug': 'rohe', 'name': '리넨 블레이저', 'slug': 'rohe-linen-blazer', 'description': '에포트리스 유러피안 무드의 핵심 아이템', 'product_type': 'outerwear', 'usage': 'casual', 'price_min': 500000, 'price_max': 800000, 'release_year': 2024, 'specs': {'price_range': '50만~80만', 'country': '네덜란드', 'founded_year': '2014', 'key_item': '리넨 블레이저'}, 'scores': {'design': 78, 'quality': 72, 'trend': 65, 'value': 32}},
    {'brand_slug': 'kiko-kostadinov', 'name': '아식스 콜라보 스니커즈', 'slug': 'kiko-asics-collab', 'description': '아방가르드 스니커즈의 정점. 컬렉터 필수 아이템', 'product_type': 'shoes', 'usage': 'street', 'price_min': 250000, 'price_max': 500000, 'release_year': 2023, 'specs': {'price_range': '25만~50만', 'country': '영국', 'founded_year': '2016', 'key_item': '아식스 콜라보'}, 'scores': {'design': 85, 'quality': 75, 'trend': 60, 'value': 30}},
    {'brand_slug': 'andersson-bell', 'name': '니트 가디건', 'slug': 'andersson-bell-cardigan', 'description': '파리 패션위크 진출 K-패션의 시그니처', 'product_type': 'knitwear', 'usage': 'casual', 'price_min': 200000, 'price_max': 400000, 'release_year': 2023, 'specs': {'price_range': '20만~40만', 'country': '한국', 'founded_year': '2014', 'key_item': '니트 가디건'}, 'scores': {'design': 72, 'quality': 68, 'trend': 62, 'value': 35}},
    {'brand_slug': 'wooyoungmi', 'name': '테일러드 수트', 'slug': 'wooyoungmi-suit', 'description': '파리 남성 패션위크 정규 쇼의 시그니처 테일러링', 'product_type': 'outerwear', 'usage': 'formal', 'price_min': 1500000, 'price_max': 3000000, 'release_year': 2023, 'specs': {'price_range': '150만~300만', 'country': '한국', 'founded_year': '2002', 'key_item': '테일러드 수트'}, 'scores': {'design': 75, 'quality': 78, 'trend': 55, 'value': 42}},
    {'brand_slug': 'jacquemus', 'name': '르 치키토 미니백', 'slug': 'jacquemus-le-chiquito', 'description': '미니백 트렌드의 시작점. 손가락 한 마디 크기의 아이코닉 백', 'product_type': 'bag', 'usage': 'casual', 'price_min': 500000, 'price_max': 800000, 'release_year': 2018, 'specs': {'price_range': '50만~80만', 'country': '프랑스', 'founded_year': '2009', 'key_item': '르 치키토'}, 'scores': {'design': 78, 'quality': 68, 'trend': 58, 'value': 35}},

    # ---- 평민(D) 브랜드 대표 아이템 ----
    {'brand_slug': 'off-white', 'name': '화살표 로고 후디', 'slug': 'off-white-arrow-hoodie', 'description': '버질 아블로의 유산. 한때 하이프의 상징이었던 시그니처', 'product_type': 'knitwear', 'usage': 'street', 'price_min': 500000, 'price_max': 800000, 'release_year': 2015, 'specs': {'price_range': '50만~80만', 'country': '이탈리아', 'founded_year': '2012', 'key_item': '화살표 후디'}, 'scores': {'design': 65, 'quality': 62, 'trend': 30, 'value': 28}},
    {'brand_slug': 'gucci-fashion', 'name': 'GG 마몽 백', 'slug': 'gucci-gg-marmont', 'description': '더블G 로고의 아이코닉 백. 알레산드로 미켈레 시대의 유산', 'product_type': 'bag', 'usage': 'casual', 'price_min': 2000000, 'price_max': 3500000, 'release_year': 2016, 'specs': {'price_range': '200만~350만', 'country': '이탈리아', 'founded_year': '1921', 'key_item': 'GG 마몽'}, 'scores': {'design': 60, 'quality': 78, 'trend': 38, 'value': 50}},
    {'brand_slug': 'balenciaga', 'name': '트리플S 스니커즈', 'slug': 'balenciaga-triple-s', 'description': '어글리 슈즈 트렌드를 만든 장본인. 지금은 논란의 브랜드', 'product_type': 'shoes', 'usage': 'street', 'price_min': 1200000, 'price_max': 1500000, 'release_year': 2017, 'specs': {'price_range': '120만~150만', 'country': '프랑스', 'founded_year': '1917', 'key_item': '트리플S'}, 'scores': {'design': 62, 'quality': 68, 'trend': 30, 'value': 42}},
    {'brand_slug': 'fear-of-god', 'name': 'Essentials 후디', 'slug': 'fog-essentials-hoodie', 'description': '대중화가 브랜드 가치를 희석시킨 대표 사례', 'product_type': 'knitwear', 'usage': 'street', 'price_min': 80000, 'price_max': 150000, 'release_year': 2018, 'specs': {'price_range': '8만~15만', 'country': '미국', 'founded_year': '2013', 'key_item': '에센셜즈 후디'}, 'scores': {'design': 55, 'quality': 58, 'trend': 28, 'value': 25}},
    {'brand_slug': 'thom-browne', 'name': '삼색 스트라이프 수트', 'slug': 'thom-browne-suit', 'description': '숏 수트의 원조. 디자인은 인정받지만 팬덤이 좁음', 'product_type': 'outerwear', 'usage': 'formal', 'price_min': 3000000, 'price_max': 6000000, 'release_year': 2010, 'specs': {'price_range': '300만~600만', 'country': '미국', 'founded_year': '2001', 'key_item': '숏 수트'}, 'scores': {'design': 78, 'quality': 82, 'trend': 28, 'value': 38}},
    {'brand_slug': 'vetements', 'name': 'DHL 프린트 티셔츠', 'slug': 'vetements-dhl-tee', 'description': '2016년 하이프의 아이콘. 지금은 브랜드 자체가 추억', 'product_type': 'knitwear', 'usage': 'street', 'price_min': 300000, 'price_max': 500000, 'release_year': 2016, 'specs': {'price_range': '30만~50만', 'country': '스위스', 'founded_year': '2014', 'key_item': 'DHL 티셔츠'}, 'scores': {'design': 52, 'quality': 50, 'trend': 18, 'value': 22}},
]


class Command(BaseCommand):
    help = '제품(모델) 시드 데이터 생성'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='기존 제품 데이터 삭제 후 재생성',
        )
        parser.add_argument(
            '--category',
            type=str,
            help='특정 카테고리만 생성 (running-shoes, chicken, mens-watch)',
        )

    def handle(self, *args, **options):
        if options['clear']:
            self.stdout.write('기존 제품 데이터 삭제 중...')
            ProductScore.objects.all().delete()
            ProductSpec.objects.all().delete()
            Product.objects.all().delete()

        category_filter = options.get('category')

        # 카테고리별 데이터 처리
        data_map = {
            'running-shoes': RUNNING_SHOES_DATA,
            'chicken': CHICKEN_DATA,
            'mens-watch': MENS_WATCH_DATA,
            'fashion-brands': FASHION_BRANDS_DATA,
        }

        for cat_slug, products in data_map.items():
            if category_filter and category_filter != cat_slug:
                continue

            try:
                category = Category.objects.get(slug=cat_slug)
            except Category.DoesNotExist:
                self.stdout.write(
                    self.style.WARNING(f'카테고리 {cat_slug}를 찾을 수 없음. seed_categories 먼저 실행 필요')
                )
                continue

            self.stdout.write(f'\n{category.icon} {category.name} 제품 생성 중...')

            for product_data in products:
                brand_slug = product_data.pop('brand_slug')
                specs_data = product_data.pop('specs', {})
                scores_data = product_data.pop('scores', {})

                try:
                    brand = Brand.objects.get(slug=brand_slug)
                except Brand.DoesNotExist:
                    self.stdout.write(
                        self.style.WARNING(f'  브랜드 {brand_slug}를 찾을 수 없음. 스킵')
                    )
                    continue

                # 제품 생성/업데이트
                product, created = Product.objects.update_or_create(
                    slug=product_data['slug'],
                    defaults={
                        'brand': brand,
                        'category': category,
                        'name': product_data['name'],
                        'description': product_data.get('description', ''),
                        'product_type': product_data.get('product_type', ''),
                        'usage': product_data.get('usage', ''),
                        'price_min': product_data.get('price_min', 0),
                        'price_max': product_data.get('price_max', 0),
                        'release_year': product_data.get('release_year'),
                        'version_number': product_data.get('version_number', 1),
                    }
                )

                # 스펙 생성/업데이트
                for key, value in specs_data.items():
                    ProductSpec.objects.update_or_create(
                        product=product,
                        key=key,
                        defaults={'value': str(value)}
                    )

                # 점수 생성/업데이트 및 티어 점수 계산
                total_score = 0
                total_weight = 0
                score_defs = category.score_definitions or []

                for key, value in scores_data.items():
                    ProductScore.objects.update_or_create(
                        product=product,
                        key=key,
                        defaults={'value': float(value)}
                    )
                    # 가중치 점수 계산
                    for d in score_defs:
                        if d.get('key') == key:
                            weight = d.get('weight', 0)
                            total_score += float(value) * weight
                            total_weight += weight
                            break

                # 티어 점수 업데이트
                if total_weight > 0:
                    product.tier_score = total_score / total_weight
                    product.save()

                action = '생성' if created else '업데이트'
                self.stdout.write(
                    f'  {product.tier}티어 {product.name} {action} (점수: {product.tier_score:.1f})'
                )

        self.stdout.write(self.style.SUCCESS('\n제품 시드 데이터 생성 완료!'))
        self.stdout.write(f'  총 제품 수: {Product.objects.count()}개')
        self.stdout.write(f'  제품 스펙: {ProductSpec.objects.count()}개')
        self.stdout.write(f'  제품 점수: {ProductScore.objects.count()}개')
